Jondolf/avian

Cargo.lock, README.md, crates/bevy_xpbd_2d/Cargo.toml, crates/bevy_xpbd_2d/examples/chain2d.rs, crates/bevy_xpbd_2d/examples/fixed_joint_2d.rs, crates/bevy_xpbd_2d/examples/move_marbles.rs, crates/bevy_xpbd_2d/examples/prismatic_joint_2d.rs, crates/bevy_xpbd_2d/examples/revolute_joint_2d.rs, crates/bevy_xpbd_3d/Cargo.toml, crates/bevy_xpbd_3d/examples/chain3d.rs, crates/bevy_xpbd_3d/examples/cubes.rs, crates/bevy_xpbd_3d/examples/fixed_joint_3d.rs, crates/bevy_xpbd_3d/examples/prismatic_joint_3d.rs, crates/bevy_xpbd_3d/examples/revolute_joint_3d.rs, crates/bevy_xpbd_3d/examples/rolling_balls.rs, crates/examples_common_2d/Cargo.toml, crates/examples_common_2d/src/lib.rs, crates/examples_common_3d/Cargo.toml, crates/examples_common_3d/src/lib.rs, src/collision.rs, src/lib.rs, src/resources.rs, src/steps/broad_phase.rs, src/steps/integrator.rs, src/steps/mod.rs, src/steps/prepare.rs, src/steps/solver.rs, src/utils.rs
This refactors the high-level xpbd algorithm structure to take advantage of bevy_ecs schedule v3 (i.e. stageless).
The algorithm is split into two schedules, one high-level for running one high-level physics step (i.e. `DELTA_TIME`) step, and one lower-level for the inner substepping (integrate, solve etc.).
=> Initial bevy 0.10 port

src/lib.rs, src/steps/mod.rs, src/steps/prepare.rs, src/steps/sync.rs
This gets rid of an unnecessary 1 frame delay, where we'd always see the physics frame 1 frame behind their position in the physics world.
Also, when pausing, we'd previously never see the latest state.
=> Sync physics transforms at the end of the physic schedule

src/lib.rs, src/resources.rs, src/steps/prepare.rs
Closes #5
This makes the physics timestep configurable by introducing the `PhysicsTimestep` enum resource that configures how the value of the new `DeltaTime` resource is computed at each physics frame. Previously the timestep was just hardcoded at `1.0 / 60.0` (which is still the default).
`PhysicsTimestep` currently looks like this:
```rs
pub enum PhysicsTimestep {
Fixed(Scalar),
Variable {
max_dt: Scalar, // Required to make sure objects don't teleport around due to large delta time
},
}
```
In the future, it could be interesting to also make time scale configurable to allow slowing down and speeding up time.
=> Make timestep configurable and add a variable timestep

crates/bevy_xpbd_2d/Cargo.toml, crates/bevy_xpbd_3d/Cargo.toml, crates/examples_common_2d/Cargo.toml, crates/examples_common_3d/Cargo.toml
Updates dependencies to Bevy 0.10.1. This was already done implicitly, but now the patch version is set explicitly to avoid future problems.
It seems like in 0.10.1, the `bevy_core_pipeline` feature is no longer set by the `bevy_pbr` feature, so it must be set explicitly as well.
=> Update to Bevy 0.10.1

crates/bevy_xpbd_2d/examples/move_marbles.rs, src/components/mod.rs, src/constraints/penetration.rs, src/steps/solver.rs, src/utils.rs
This adds a `CoefficientCombine` enum with the `Average`, `Min`, `Multiply` and `Max` variants, where `Average` has the lowest priority, and `Max` has the highest priority (in case of conflicting combine rules). The default is still `Average` like before.
I would have also added something like `Custom(fn(a: Scalar, b: Scalar) -> Scalar)`, but it would cause issues with `Copy` and `Reflect`, so I left it out.
I also added a couple builder methods and a test for the combine rules.
Combining two `Restitution` components:
```rs
let restitution1 = Restitution::new(0.3).with_combine_rule(CoefficientCombine::Average);
let restitution2 = Restitution::new(0.7).with_combine_rule(CoefficientCombine::Multiply);
let result = Restitution::new(0.21).with_combine_rule(CoefficientCombine::Multiply); …
```
=> Add `CoefficientCombine` rule for `Restitution` and `Friction`

README.md, crates/bevy_xpbd_2d/examples/chain2d.rs, crates/bevy_xpbd_2d/examples/fixed_joint_2d.rs, crates/bevy_xpbd_2d/examples/move_marbles.rs, crates/bevy_xpbd_2d/examples/prismatic_joint_2d.rs, crates/bevy_xpbd_2d/examples/revolute_joint_2d.rs, crates/bevy_xpbd_3d/examples/chain3d.rs, crates/bevy_xpbd_3d/examples/cubes.rs, crates/bevy_xpbd_3d/examples/cubes_f64.rs, crates/bevy_xpbd_3d/examples/fixed_joint_3d.rs, crates/bevy_xpbd_3d/examples/prismatic_joint_3d.rs, crates/bevy_xpbd_3d/examples/revolute_joint_3d.rs, crates/bevy_xpbd_3d/examples/rolling_balls.rs, src/bundles.rs, src/components/mod.rs, src/tests.rs
This mainly adds more builder methods for `RigidBodyBundle`. Restitution and friction now also implement `From<Scalar>`, so you can do things like `.with_friction(0.5)` instead of having to pass the entire struct to the method.
`ColliderBundle::new()` now only takes a collider shape, and a default density of 1 is used. To specify the density manually, you can use `.with_density()`.
=> Improved APIs for bundles

crates/bevy_xpbd_2d/Cargo.toml, crates/bevy_xpbd_3d/Cargo.toml, crates/bevy_xpbd_derive/Cargo.toml, crates/bevy_xpbd_derive/README.md, crates/bevy_xpbd_derive/src/lib.rs, src/components/layers.rs, src/components/mod.rs, src/lib.rs, src/plugins/solver.rs
This adds collision filtering in the form of a `CollisionLayers` component that contains collision groups and masks. The design and implementation is heavily inspired by the dicontinued [Heron](https://github.com/jcornaz/heron).
`CollisionLayers` has many methods where the layers must implement `PhysicsLayer`. There is now a `bevy_xpbd_derive` crate that provides a derive macro for this purpose. The macro is imported in the `bevy_xpbd::prelude`.
```rust
use bevy::prelude::*;
use bevy_xpbd::prelude::*;
#[derive(PhysicsLayer)]
enum Layer {
Player,
Enemy,
Ground,
}
fn spawn(mut commands: Commands) {
commands.spawn((
Collider::ball(0.5),
// Player collides with enemies and the ground, but not with other players
CollisionLayers::new([Layer::Player], [Layer::Enemy, Layer::Ground])
));
}
```
=> Add `CollisionLayers`

src/components/collider.rs, src/plugins/solver.rs
Adds a `Sensor` component for creating colliders that generate collision events but don't cause a collision response.
```rust
commands.spawn((Collider::ball(0.5), Sensor));
```
=> Add `Sensor` component for colliders

src/components/mod.rs, src/plugins/integrator.rs, src/plugins/prepare.rs, src/plugins/sleeping.rs
Numbers have `.to_radians()`, but `AngularVelocity` is already in radians. This can lead to incorrect usage when `Deref` is implemented. For now the best solution seems to be just removing `Deref` from the 2D `AngularVelocity`.
Closes #13.
=> Remove `Deref` and `DerefMut` from `AngularVelocity` in 2D

src/plugins/solver.rs, src/resources.rs
Fixes #29.
The generalized inverse mass was being calculated based on the contact normal and not `delta_v`, so it didn't take dynamic friction into account.
In cases where the physics units used were larger, this caused explosive behaviour. Below is the `move_marbles` example, modified to use pixels instead of 3D units.
Previously it exploded when moving the marbles:
https://github.com/Jondolf/bevy_xpbd/assets/57632562/630e9b4a-8a7d-48f5-8ce0-2a18f74b3657
Now it works as expected:
https://github.com/Jondolf/bevy_xpbd/assets/57632562/feca6220-4ae6-4523-b251-38f12e08e02f
=> Fix generalized inverse mass in velocity solve

.github/workflows/ci.yml, crates/bevy_xpbd_2d/Cargo.toml, crates/bevy_xpbd_3d/Cargo.toml, src/components/collider.rs, src/lib.rs
Removes `bevy_render` from Bevy's default features to support headless usage. Adds a `collider-from-mesh` feature to still support creating colliders from Bevy meshes.
=> Add `collider-from-mesh` feature and make `bevy_render` optional

src/components/mod.rs, src/lib.rs, src/plugins/integrator.rs, src/plugins/setup.rs
Adds the `LinearDamping` and `AngularDamping` components for simulating drag and air resistance. They are optional, so no damping is applied by default.
=> Add `LinearDamping` and `AngularDamping`

src/components/mod.rs, src/lib.rs, src/plugins/integrator.rs
Expands the `ExternalForce` and `ExternalTorque` APIs by adding a `persistence` property for controlling if a force should persist across frames and by adding several methods. Forces can now be applied at a given point using `apply_at_point`, which will also apply torque. The documentation of these components is also much better.
=> Support applying force at point and automatically clearing external force and torque

src/plugins/spatial_query/mod.rs, src/plugins/spatial_query/pipeline.rs, src/plugins/spatial_query/ray_caster.rs, src/plugins/spatial_query/shape_caster.rs, src/plugins/spatial_query/system_param.rs
The entity bits contain the entity generation. This generation can be very big, which can cause QBVH allocations in the spatial query pipeline to be way too large. Using just the index and storing the generation separately fixes this.
Thanks to `NiseVoid` on the Discord for finding this.
=> Use entity index for QBVH nodes instead of entity bits

src/plugins/spatial_query/query_filter.rs
Replaces collision layers (groups and masks) with just masks in `SpatialQueryFilter`. Spatial queries don't necessarily exist as physical objects in the world, so it doesn't make sense for them to belong in groups, and this also just makes the API nicer.
Removed `with_layers` in favor of:
- `with_masks_from_bits`
- `with_masks`
```rust
// Previously
let query_filter = SpatialQueryFilter::new().with_layers(CollisionLayers::from_bits(0xffff_ffff, 0b1011));
// Now
let query_filter = SpatialQueryFilter::new().with_masks_from_bits(0b1011);
```
=> Use masks instead of collision layers for `SpatialQueryFilter`

src/components/layers.rs
Renames collision layer methods to be clearer and adds `remove_groups` and `remove_masks`.
- `with_mask` → `add_mask`
- `with_masks` → `add_masks`
- `without_mask` → `remove_mask` and `remove_masks`
- `with_group` → `add_group`
- `with_groups` → `add_groups`
- `without_group` → `remove_group` and `remove_groups`
=> Rename `CollisionLayers` methods `with_group`, `without_group` etc. to `add_group`, `remove_group`

src/plugins/spatial_query/mod.rs, src/plugins/spatial_query/ray_caster.rs, src/plugins/spatial_query/shape_caster.rs, src/plugins/spatial_query/system_param.rs
Adds support for computing multiple hits in shape casts. This also unifies the API with ray casting methods.
The main caveat is that this needs to be done using multiple best-first searches of the QBVH and adding each hit entity to the excluded entities. Using a single depth-first search would be faster, but Parry doesn't seem to support it for shape casts.
=> Support multiple hits for shape casts

src/components/locked_axes.rs, src/components/mod.rs, src/components/rotation.rs, src/components/world_queries.rs, src/constraints/angular_constraint.rs, src/constraints/position_constraint.rs, src/lib.rs, src/plugins/integrator.rs, src/plugins/setup.rs, src/plugins/solver.rs, src/plugins/spatial_query/system_param.rs
Adds a `LockedAxes` component for locking translational and rotational axes.
The locked axes are represented as a `u8`, where each axis has one bit, a total of 6 bits. There are methods like `lock_translation_x`, `lock_rotation_y` and `unlock_rotation_z`, and the constants `TRANSLATION_LOCKED`, `ROTATION_LOCKED` and `ALL_LOCKED`.
To take the locked axes into account, an effective mass/inertia is computed before applying any positional or rotational updates. For example the effective mass is just a vector where the locked axes have a mass of zero. This works similarly for other updates.
```rust
use bevy::prelude::*;
use bevy_xpbd_3d::prelude::*;
fn spawn(mut commands: Commands) {
// Spawn a capsule that only rotates around the Y axis
commands.spawn((
RigidBody::Dynamic, …
```
=> Add `LockedAxes`

src/plugins/setup.rs, src/resources.rs
I added a FixedOnce mode to physics timestep which only runce once every time the system triggers. With this change running inside FixedUpdate seems to work as intended.
I'm not sure if the behavior for physics_loop.paused is correct considering the `queued_steps` logic in the other mode.
=> Add PhysicsTimestep mode to run only once with a fixed delta

src/components/collider.rs
Implement `Debug` for colliders, which enables debug printing of the underlying collider shape and allows for structs that contain a `Collider` field to also implement `Debug` without error.
=> Implement Debug for Collider

src/plugins/mod.rs, src/plugins/spatial_query/mod.rs, src/plugins/spatial_query/pipeline.rs, src/plugins/spatial_query/ray_caster.rs, src/plugins/spatial_query/shape_caster.rs, src/plugins/spatial_query/system_param.rs, src/utils.rs
- Fixed an issue where spatial queries weren't detecting colliders of entities with a generation of over 0 (i.e. spawned multiple times)
- Fixed removal detection so that collider removals aren't missed
- Fixed shape caster `ignore_origin_penetration` that did the opposite of what it was supposed to do
- Refactored spatial query pipeline code, e.g. the pipeline now stores the colliders, so calling the query methods doesn't query the ECS to get the colliders each time
=> Fixes for spatial queries

crates/bevy_xpbd_3d/Cargo.toml, crates/bevy_xpbd_3d/examples/basic_dynamic_character.rs, crates/bevy_xpbd_3d/examples/basic_kinematic_character.rs
Adds very basic examples for a dynamic and a kinematic character controller with directional movement and jumping. The kinematic example also shows how to implement a basic collision response.
https://github.com/Jondolf/bevy_xpbd/assets/57632562/9024e9d2-8a29-4995-8ed4-5e7386f9a9ae
=> Add basic dynamic and kinematic character controller examples

crates/bevy_xpbd_2d/examples/many_shapes.rs, src/constraints/joints/fixed.rs, src/constraints/joints/mod.rs, src/constraints/joints/prismatic.rs, src/constraints/joints/revolute.rs, src/constraints/joints/spherical.rs, src/lib.rs, src/plugins/debug/configuration.rs, src/plugins/debug/mod.rs
Adds several methods for `PhysicsDebugConfig` and `DebugRender` to make the API much nicer, and adds support for debug rendering entity axes and joints.
An example of a global config that renders colliders and hides the visual meshes, but disables all debug rendering for a specific entity:
```rust
app.insert_resource(
PhysicsDebugConfig::colliders(Color::ORANGE).with_mesh_visibility(false)
);
// In some setup system
commands.spawn((
RigidBody::Dynamic,
Collider::ball(0.5),
DebugRender::none(),
));
```
Closes #75 (although it was already possible, just with a more cumbersome API)
=> Add debug rendering axes and joints and improve configuration API

src/plugins/spatial_query/pipeline.rs, src/plugins/spatial_query/system_param.rs
This allows using spatial queries outside systems, for example in `AsyncComputePool`.
`SpatialQuery` methods remain, but now they delegate to `SpatialQueryPipeline`.
After this change I'm wondering if `SpatialQuery` is even necessary. It uses `ResMut` internally, which means systems performing queries can't run in parallel. The only method taking `&mut self` is `update_pipeline`. Thus, I propose removing `SpatialQuery` and adding `update_spatial_query_pipeline` system, which would be added to `PostUpdate` by default (and additional copies could be added by users). All user code would have to change `SpatialQuery` to `Res<SpatialQueryPipeline>`.
=> Move `SpatialQuery` methods to `SpatialQueryPipeline`

src/plugins/debug/configuration.rs, src/plugins/debug/mod.rs
This allows easily turning debug renderer on and off by changing `enabled` field of `PhysicsDebugConfig`
Also it matches similar approach by `GizmoConfig` from bevy and `DebugRenderContext` from rapier.
=> Add `enabled` flag to `PhysicsDebugConfig` to globally disable debug rendering at runtime

src/lib.rs, src/plugins/setup.rs, src/resources.rs
I can't think of much to say about this change right now. 
If something is unclear, please ask. Thanks for your work and your time!
=> Add PhysicsTimescale resource for slow-motion or fast-forward simulation

src/constraints/penetration.rs
The center of mass used in `PenetrationConstraint` was local when it should have been in world space.
=> Use world-space center of mass in penetration constraint

src/plugins/spatial_query/mod.rs, src/plugins/spatial_query/ray_caster.rs, src/plugins/spatial_query/shape_caster.rs
Hits are now cleared automatically when the `RayCaster`/`ShapeCaster` is disabled.
=> Add `clear` methods for ray and shape hits and clear the hits on disable

src/plugins/broad_phase.rs
Previously, AABBs were expanded equally in all directions based on the velocity of the body in order to avoid missing potential collisions during the broad phase. However, expanding the AABBs in the direction opposite of the movement direction is unnecessary.
This PR changes it so that AABBs are only expanded in the direction of the linear velocity. The angular velocity still expands AABBs in all directions regardless of the shape, but that can maybe be addressed in another PR.
This is how AABBs look now: (gizmos have a delay, so it can often look like the AABBs are still expanded behind the bodies; this is not actually the case)
https://github.com/Jondolf/bevy_xpbd/assets/57632562/cbdeb58a-a8eb-43b5-b086-da3cf571e2bc
This also gives a significant performance boost for situations with …
=> Expand AABBs only in the movement direction

crates/bevy_xpbd_3d/examples/cubes.rs, src/collision.rs, src/components/mod.rs, src/components/world_queries.rs, src/constraints/joints/mod.rs, src/constraints/joints/prismatic.rs, src/constraints/penetration.rs, src/constraints/position_constraint.rs, src/lib.rs, src/plugins/integrator.rs, src/plugins/prepare.rs, src/plugins/setup.rs, src/plugins/solver.rs, src/utils.rs
During integration and constraint solving, position gets incremented by very small amounts, especially at high substep count.  When the objects are far from origin, small increments to position are rounded to zero. To mitigate that, I've added `AccumulatedTranslation` component, which gets incremented instead of `Position`. Then, at the end of each substep, a system updates the actual position.
This change seems to be the magic bullet for "far from origin" kinds of problems. But it's not perfect yet.
Here's the cubes example with origin set to (10000, 10000). When using `f32`, the next float after `10000` is `10000.0009766`, which gives precision of roughly `1e-3` . 
Here's the before:
https://github.com/Jondolf/bevy_xpbd/assets/42153076/3e96809b-8cfa-4fc2-b288-05c8a2c4f37e
Here's the …
=>  Improve simulation stability when object are far from world origin 

src/collision.rs, src/constraints/penetration.rs
#84 changed contact positions to be local in order to improve numerical stability. However, `Contact` should also have the global contact positions, as users and e.g. the debug plugin often need global coordinates, and it's unnecessry to do extra component queries just to convert into global coordinates manually.
This PR renames `point1` and `point2` to `local_point1` and `local_point2` and adds back the original `point1` and `point2` that were in global coordinates. This also fixes the debug plugin contact rendering, which was broken by #84.
=> Add back global contact positions

crates/bevy_xpbd_3d/examples/basic_kinematic_character.rs, src/collision.rs, src/constraints/penetration.rs, src/plugins/debug/mod.rs, src/plugins/solver.rs
Currently, each collision only uses one contact. When a box is on the ground, the contact point oscillates between the corners, which can often cause significant instability and positional drift.
This PR changes this behaviour by computing multiple contact points using contact manifolds. This allows all four corners of a cube to be in contact at the same time, which essentially eliminates drifting, closing #85.
Before: 
https://github.com/Jondolf/bevy_xpbd/assets/57632562/5aeaa265-ce15-465b-9eab-42a732a1f657
After:
https://github.com/Jondolf/bevy_xpbd/assets/57632562/a4136550-0872-442c-ad36-cbf4d105e1d0
As you can see, the cubes now land in a much more stable way, drifting is almost nonexistent, and explosions or small jumps are significantly reduced.
Edit: Fixed this for convex …
=> Use contact manifolds instead of single contacts for collisions

src/collision.rs
Hi, i have huge performance issues due to the method `penetration_constraints`. I will try to investigate further in this field to get the most of performance out, but im still learning, so making progress is especially for me hard.
I made this little change and thought maybe it is useful so i try a PR ^^ And it at least helped me to support a little more collider amount then before. If its non sense, then feel free to correct me and close this :) Anyway thanks for reading.
=> Filter operation reodered for a little performance boost

src/collision.rs, src/constraints/penetration.rs, src/plugins/debug/mod.rs, src/plugins/solver.rs
Currently, contact normals are stored in world-space. However, the directions can slightly change during each constraint solve, which can cause positional drift.
This PR stores contact normals and contact points in local space and transforms them into world-space in each penetration constraint and the velocity solve. `ContactData` has helper methods for conversion to global space, although they require the rotation and/or position of the body.
Stacking cubes is now *much* more stable. Below is a screenshot of an 80 cube stack, with f32 precision, with sleeping disabled, after nearly 5 minutes of simulation.
Previously, the same stack fell in about 3 seconds due to cubes moving sideways.
Note that perfectly stable stacks require a lot of substeps (I think I used 80 or 90 for the test), but …
=> Store local contact normals and transform them into world-space at each solve

src/lib.rs, src/plugins/mod.rs, src/plugins/sync.rs, src/tests.rs
Currently, the only way to move and position bodies after initialization is to use the `Position` and `Rotation` components. Using these separate components has many benefits over using `Transform` for physics, as discussed in #16.
However, if we want Bevy XPBD to feel as integrated into Bevy as possible, it would make sense to allow using `Transform` directly for moving bodies, as it is what Bevy and the rest of its ecosystem typically uses. This would also allow third party crates to move bodies in a more backend-agnostic way without having to have explicit support for Bevy XPBD.
This PR adds a new synchronization system for `SyncPlugin` that updates `Position` and `Rotation` based on changes in `GlobalTransform`. This does *not* replace the separate components, but rather adds another …
=> Support `Transform` for moving and positioning bodies

crates/bevy_xpbd_2d/examples/ray_caster.rs, src/plugins/broad_phase.rs, src/plugins/prepare.rs, src/plugins/sync.rs
This PR adds the `Position` and `Rotation` components for colliders automatically. Colliders can also be moved using `Transform`, just like rigid bodies.
=> Automatically add `Position` and `Rotation` for colliders

crates/bevy_xpbd_2d/examples/distance_joint_2d.rs, crates/bevy_xpbd_3d/examples/distance_joint_3d.rs, src/constraints/joints/distance.rs, src/constraints/joints/mod.rs, src/constraints/mod.rs, src/plugins/debug/mod.rs, src/plugins/solver.rs
Hi,
This is a really cool project you've put together. I was using Rapier before this, and I really wanted a spring joint which isn't supported there. I hoped to find it here, but better than finding it I found that the XPBD means of expressing constraints and joints is so much easier to work with that I put one together myself that I hope you'll find useful. 
Taking note from other XPBD implementations, I called this a DistanceJoint. When it's compliance does not equal 0 though it very much behaves like a spring joint.
I added examples in 2D and 3D. Here are some gifs on them.
One problem I didn't tackle was if you look at the heading describing a SphericalJoint and a DistanceJoint, they're not terribly distinct. However, upon inspection SphericalJoint is doing more than DistanceJoint. I …
=> feature: Add DistanceJoint and 2D and 3D examples.

crates/bevy_xpbd_3d/examples/distance_joint_3d.rs, src/plugins/debug/configuration.rs, src/plugins/debug/mod.rs
Changes rigid body axes to be debug rendered at the center of mass instead of the rigid body position.
=> Debug render rigid body axes at center of mass

crates/bevy_xpbd_3d/examples/chain_3d.rs
This change adds a ui that explains how to move around the chain in the `chain_3d`  example in `bevy_xpbd_3d`
The text says `"Use Arrow Keys to Move The Chain"`
=> Added text that explained how to use the example 'chain_3d'

src/components/mod.rs
Adds the "Bounciness" and "Elasticity" aliases for the `Restitution` component.
Closes #113.
=> Add "Bounciness" and "Elasticity" aliases for `Restitution`

src/components/mod.rs, src/lib.rs, src/plugins/prepare.rs
Clamps each `Restitution` coefficient to be between 0 and 1, adds the associated constants `Restitution::PERFECTLY_INELASTIC` and `Restitution::PERFECTLY_ELASTIC`, and significantly improves the restitution docs. This closes #114 and #115.
The clamping avoids issues with unrealistic and explosive behavior when users try to use values that are negative or over 1, which makes things more user-friendly and realistic. For the rare cases where you want bodies to gain kinetic energy on contact, you should implement it manually to work for your specific case in a stable manner.
The main caveat is that you can no longer multiply e.g. 0.5 and 2.0 to get 1.0 when combining coefficients, since 2.0 gets clamped to 1.0, which results in a final coefficient of 0.5. However, I find this clamping to be …
=> Clamp coefficient of restitution between 0 and 1 and improve restitution docs

crates/bevy_xpbd_3d/examples/custom_constraint.rs, src/components/world_queries.rs, src/constraints/joints/distance.rs, src/constraints/joints/mod.rs, src/constraints/joints/prismatic.rs, src/constraints/penetration.rs
Adds a `current_position` getter method for `RigidBodyQueryItem`. This computes the sum of `Position` and `AccumulatedTranslation`, which is more convenient and avoids issues where you forget to add the accumulated translation in e.g. custom constraints.
=> Add `current_position` getter for `RigidBodyQueryItem`

src/plugins/setup.rs
Registers `CoefficientCombine` so that `Friction` and `Restitution` can be deserialized.
=> Register `CoefficientCombine`

src/components/mass_properties.rs, src/components/world_queries.rs
Previously, the combined center of mass of a body and its collider was computed as `com1 + com2`, but this doesn't take into account different masses. The combined inertia was also computed as `inertia1 + inertia2` without taking into account mass or the center of mass, i.e. the offset.
This PR fixes the center of mass issue by computing it correctly like `(com1 * mass1 + com2 * mass2) / (mass1 + mass2)`, and the inertia issue by first shifting the inertia values by the relative center of mass. Subtracting mass properties is handled similarly, but by simply using `-` instead of `+` in many places. These fixes will be very important especially when we implement child colliders.
I also added tests to verify that the mass and center of mass are correct after adding or subtracting mass …
=> Fix center of mass and inertia computations and add tests

src/plugins/spatial_query/pipeline.rs, src/plugins/spatial_query/system_param.rs
When users only want do callback on spatial queries, avoid unnecessary allocate. (ray_hits,shape_hits,point_intersections still return results)
=> Avoid allocate on spatial queries. ray_hits_callback, shape_hits_callback, intersections_callback

src/plugins/sync.rs
Fixes #125 
child's `Transform.translation.z` was previously added twice, in `extend()` and `reparented_to()`
This change removes the addition that was in `extend()`.
=> Fix 2d `position_to_transform` changing child `Transform` z-component

src/components/rotation.rs
DQuat / Scalar are already PartialEq, so we can derive this for Rotation too.
=> Make Rotation & PreviousRotation derive PartialEq

src/components/world_queries.rs
With these changes, `cargo test` passes on my apple m1 max
=> Fix tests on mac m1

src/plugins/prepare.rs
Currently, the transforms of bodies and colliders that are children are initialized incorrectly by the `PreparePlugin`. The `Transform` is assumed to be the same as `GlobalTransform` when updating `Transform` based on `Position` and `Rotation`.
This PR fixes the issue by computing the correct local transform based on the difference between the parent's and child's global positions/rotations.
- Moved the transform initialization, which was previously in both `init_rigid_bodies` and `init_colliders`, into a separate system `init_transforms`
- `apply_deferred` is now called before the initialization systems
- Transform propagation is run if either rigid bodies or colliders have been added instead of just for new rigid bodies
- Added more comments for systems
- Removed some separate type …
=> Fix `Transform` initialization for children and refactor `prepare.rs`

src/components/forces.rs
In #123, the docs were changed to say that forces are local. However, they're actually in world space, which is the case for most other physics engines as well.
This PR fixes the docs and adds a section about applying local forces or impulses.
=> Clarify that forces are in world space and improve force docs

src/plugins/prepare.rs
Removes individual `insert` calls in `prepare.rs` in favor of single calls that add multiple components at once. This reduces the archetype count significantly.
For a MinimalPlugins setup with just cuboid rigid bodies, the archetype count went from 26 to 5. It could probably still be reduced by a few archetypes, but it would maybe hurt code quality/modularity a bit.
=> Combine `insert` calls into bundles to reduce archetype count

src/plugins/spatial_query/mod.rs, src/plugins/spatial_query/pipeline.rs, src/plugins/spatial_query/system_param.rs
The incremental updates on Qbvh don't work as intended, an issue about this has been open on rapier/parry for a long time but the issues are yet to be solved. For now it's faster and more stable to rebuild the Qbvh entirely ever frame.
=> Avoid incremental updates to Qbvh

crates/bevy_xpbd_2d/examples/one_way_platform_2d.rs, src/lib.rs, src/plugins/narrow_phase.rs, src/plugins/setup.rs
Create a stage to allow filtering and changing collisions from user-defined systems.
This is the simplest part of #150: the Global Physics hooks via user systems only.
- Adds `SubstepSet::PostProcessCollisions`, which is directly after `SubstepSet::NarrowPhase`
- Adds `PostProcessCollisionsSchedule`, which is run in `SubstepSet::PostProcessCollisions`
- Exposes `retain` from `Collisions` to allow direct modification of the set of collisions
Also includes a simple one-way-platform example.
=> Collision post processing

src/components/collider.rs
Unity calls sensors triggers, so it's good to have that as an alias. I also made the sensor docs a bit clearer.
=> Add `Trigger` alias for `Sensor` and improve `Sensor` docs

src/plugins/setup.rs, src/plugins/sync.rs
Closes #165, enabling better determinism in rollback-contexts when modifying transforms.
=> Make `PreviousGlobalTransform` public and derive traits

crates/bevy_xpbd_2d/snapshots/bevy_xpbd_2d__tests__body_with_velocity_moves.snap, crates/bevy_xpbd_3d/snapshots/bevy_xpbd_3d__tests__body_with_velocity_moves.snap, src/plugins/prepare.rs, src/plugins/setup.rs, src/tests.rs
Added an apply_deferred to ensure all the physics components get added that frame - otherwise the body won't be simulated until commands are flushed later.
HOWEVER, the added test will still fail because it appears that delta_seconds is 0 for the first update here:
https://github.com/RJ/bevy_xpbd/blob/c61a90ec03ba51b74354053eca9ac8c7f09d1f59/src/plugins/setup.rs#L260
meaning the ` physics_loop.accumulator` doesn't increase on the first update, because it was referencing `delta_seconds`. I *think* it makes more sense to use `dt` there, since it's already been scaled and clamped as needed.
This fixes the test, but only because it's not using a Variable timestep, which would still fail because there is no delta_seconds on the first update. I don't think it's the fault of the manual time …
=> Ensure newly created bodies get simulated the frame they are added

.github/workflows/pull_request_template.md
Currently, there is no template for pull requests. It would be good to have a rough structure to follow to make reviewing changes easier.
This PR adds a PR template that is mostly a copy of Bevy's PR template.
=> Add PR template

crates/bevy_xpbd_2d/examples/one_way_platform_2d.rs, src/components/collider.rs, src/plugins/narrow_phase/contact_data.rs, src/plugins/narrow_phase/mod.rs, src/plugins/solver.rs
The API for the `Collisions` resource is still lacking some important methods, and it doesn't have any high-level docs.
I added the following methods for `Collisions`:
- `get_internal`/`get_internal_mut`
- `contains`
- `insert_collision_pair`
- `extend`
- `remove_collision_pair`
I also moved `Collisions`, `Contacts`, `ContactManifold` and `ContactData` into a new module since they were making the narrow phase module a bit verbose and difficult to follow.
`Collisions` is also much more documented now.
=> Improve `Collisions` API and docs

README.md, src/components/mod.rs, src/components/world_queries.rs, src/constraints/angular_constraint.rs, src/constraints/position_constraint.rs, src/lib.rs, src/plugins/setup.rs, src/plugins/solver.rs
Closes #177.
Many physics engines like Rapier and PhysX support specifying the *dominance* of a dynamic rigid body. Bodies with a higher dominance act as if they had infinite mass during interactions, which can be useful for things like players pushing objects or cameras that collide with objects but don't exert forces on them.
Add a `Dominance` component with an `i8` that controls the dominance of a body. The default dominance is `0`, but static and kinematic bodies will always have a higher dominance than dynamic bodies.
```rust
use bevy::prelude::*;
use bevy_xpbd_3d::prelude::*;
// Player dominates all dynamic bodies with a dominance lower than 5
fn spawn_player(mut commands: Commands) {
commands.spawn((
RigidBody::Dynamic,
Collider::capsule(1.0, 0.4),
Dominance(5),
));
}
```
=> Add `Dominance`

src/plugins/debug/configuration.rs, src/plugins/debug/mod.rs
The debug renderer doesn't display whether bodies are sleeping.
Add a "sleeping color multiplier" that multiplies the HSLA properties of colors used for colliders, AABBs and joints when the bodies are sleeping. By default, it just makes the colors darker for sleeping bodies.
The multiplier can be configured with `PhysicsDebugConfig` and `DebugRender`.
=> Add debug rendering for sleeping bodies

crates/bevy_xpbd_3d/examples/custom_constraint.rs, src/constraints/joints/distance.rs, src/constraints/joints/fixed.rs, src/constraints/joints/mod.rs, src/constraints/joints/prismatic.rs, src/constraints/joints/revolute.rs, src/constraints/joints/spherical.rs, src/constraints/mod.rs, src/constraints/penetration.rs, src/plugins/spatial_query/ray_caster.rs, src/plugins/spatial_query/shape_caster.rs
For bevy_ggrs and other snapshot/save/load/scenes functionality to work the `MapEntities` trait is needed in order to fix entity ids after loading.
Implement `MapEntities` for the components that have `Entity`s as fields.
---
- Components now implement `MapEntities`
- The `XpbdConstraint` trait now requires `MapEntities` if you implemented custom `XpbdConstraint`s you should now implement the `MapEntities` trait on your types.
=> Map entities

src/components/collider.rs, src/components/mass_properties.rs, src/components/mod.rs, src/components/world_queries.rs, src/plugins/prepare.rs, src/plugins/setup.rs
Setting the density of a collider is currently unnecessarily verbose and limiting. It requires giving the collider and density to a method that creates the mass property component:
```rust
ColliderMassProperties::new_computed(&Collider::ball(0.5), 2.5)
```
This makes it basically impossible to specify the density when the collider isn't known in advance, like for async colliders #190, and the API is just very inconvenient.
Add a `ColliderDensity` component. The above becomes just this:
```rust
ColliderDensity(2.5)
```
Because `ColliderMassProperties` is always overwritten using this density, I also made its properties completely read-only with getter methods.
---
- Added `ColliderDensity`
- Added `Collider::mass_properties`
- Renamed `ColliderMassProperties::new_computed` to …
=> Add `ColliderDensity`

src/components/world_queries.rs, src/plugins/solver.rs
When a dynamic body is spawned overlapping another rigid body, it can gain a lot of velocity, which causes explosive behavior. This can currently be a bit unclear for users who aren't familiar with the internals of the engine.
Print a warning when a dynamic body is overlapping with another body at spawn. The warning is in the following format:
```rust
warn!(
"{:?} and {:?} are overlapping at spawn, which can result in explosive behavior.",
body1.entity, body2.entity,
);
```
We could have an option to make these overlapping scenarios gently move the bodies into a non-penetrating state rather than cause a large burst of velocity.
=> Warn about explosive behavior caused by overlapping at spawn

crates/bevy_xpbd_3d/examples/basic_dynamic_character.rs, crates/bevy_xpbd_3d/examples/basic_kinematic_character.rs, src/plugins/spatial_query/mod.rs, src/plugins/spatial_query/ray_caster.rs, src/plugins/spatial_query/shape_caster.rs
People often use ray and shape casters on entities with colliders, but don't want to count hits against those colliders. This currently requires tinkering with `ignore_origin_penetration`, `excluded_entities` or collision layers, which is very inconvenient. People expect the caster to ignore its own collider by default since you very rarely need to detect hits against it.
Add an `ignore_self` property for `RayCaster` and `ShapeCaster`. It's true by default, but can be configured like `.with_ignore_self(false)`.
=> Add `ignore_self` property for `RayCaster` and `ShapeCaster`

crates/bevy_xpbd_2d/Cargo.toml, crates/bevy_xpbd_3d/Cargo.toml, src/lib.rs, src/plugins/debug/configuration.rs, src/plugins/debug/mod.rs, src/plugins/mod.rs
Currently, the `PhysicsDebugPlugin` is behind a feature flag that isn't enabled by default. Because of this, it also isn't linked nicely in the docs, and we can't have a debug rendering example without requiring users to add feature flags manually. This makes it a bit less discoverable and a bit inconvenient.
Make `debug-plugin` a default feature and improve the debug rendering docs, also adding code examples. Debug rendering can now be enabled by adding the `PhysicsDebugPlugin`.
---
If you want to enable debug rendering, just having the `debug-render` feature enabled isn't enough. You also need to add `PhysicsDebugPlugin` manually.
=> Make `debug-plugin` a default feature and improve docs

crates/examples_common_3d/Cargo.toml
When running the async colliders example, the following warnings are printed, and Ferris does not appear.
```
2023-10-27T23:27:51.794954Z  WARN bevy_gltf::loader: Error loading glTF texture: You may need to add the feature for the file format: failed to load an image: The image format Png is not supported
2023-10-27T23:27:51.794964Z  WARN bevy_gltf::loader: Error loading glTF texture: You may need to add the feature for the file format: failed to load an image: The image format Png is not supported
2023-10-27T23:27:51.794967Z  WARN bevy_gltf::loader: Error loading glTF texture: You may need to add the feature for the file format: failed to load an image: The image format Png is not supported
```
- Enable bevy's png feature in the 3d examples
=> Enable bevy's png feature in the 3d examples

crates/bevy_xpbd_2d/examples/chain_2d.rs, crates/bevy_xpbd_2d/examples/many_shapes.rs, crates/bevy_xpbd_2d/examples/move_marbles.rs, crates/bevy_xpbd_2d/examples/one_way_platform_2d.rs, crates/bevy_xpbd_3d/examples/basic_dynamic_character.rs, crates/bevy_xpbd_3d/examples/basic_kinematic_character.rs, crates/bevy_xpbd_3d/examples/chain_3d.rs, crates/bevy_xpbd_3d/examples/cubes.rs, crates/bevy_xpbd_3d/examples/custom_constraint.rs, crates/bevy_xpbd_3d/examples/distance_joint_3d.rs, crates/bevy_xpbd_3d/examples/fixed_joint_3d.rs, crates/bevy_xpbd_3d/examples/prismatic_joint_3d.rs, crates/bevy_xpbd_3d/examples/revolute_joint_3d.rs
Fixes #170.
Currently, the movement in examples like `move_marbles` and `cubes` is frame rate dependent because they are running in `Update` but don't use delta time. `basic_dynamic_character` and `basic_kinematic_character` on the other hand run in the `PhysicsSchedule`, but this can cause issues with missed inputs as reported in #170.
The character controllers are also perhaps too basic and don't reflect real usage well, and the movement code isn't great and it doesn't support WASD.
- Put all movement systems in `Update` and use delta time (alternatively, you could send input events in `Update` and have another system handle the movement in the `PhysicsSchedule`)
- Refactor input handling to be cleaner and to support WASD as well as arrow keys
- Refactor character controller examples …
=> Improve movement in examples

crates/bevy_xpbd_3d/examples/basic_dynamic_character.rs, crates/bevy_xpbd_3d/examples/basic_kinematic_character.rs
The character controller examples currently only support keyboard input and have input handling and movement in the same system. It would be good to have the examples be more complete while encouraging good practises (like separate input handling), especially since we don't have a built-in character controller.
Split the movement system into parts. `keyboard_input` and `gamepad_input` send `MovementAction` events which are handled by the `movement` system.
=> Refactor character controller examples and support gamepad input

.github/workflows/ci.yml
Main change is updating the version of Node used to keep ahead of GitHub's deprecations.
https://github.com/actions/checkout/blob/main/CHANGELOG.md
- Keep up to date with current version of the GitHub checkout action.
- Update to the current version.
=> Update to `actions/checkout@v4`.

crates/bevy_xpbd_3d/examples/trimesh_shapes_3d.rs, src/lib.rs, src/plugins/collision/mod.rs, src/plugins/spatial_query/pipeline.rs
- Don't have warnings from `clippy::doc_markdown`.
- Have nicely formatted API docs.
- Use backticks more!
=> docs: Use more backticks.

src/components/collider.rs, src/components/forces.rs, src/components/layers.rs, src/components/locked_axes.rs, src/components/mass_properties.rs, src/components/mod.rs, src/plugins/collision/mod.rs, src/plugins/spatial_query/mod.rs, src/plugins/spatial_query/ray_caster.rs, src/plugins/spatial_query/system_param.rs
- Use intradoc links correctly rather than a mix of the old HTML link syntax.
- Hopefully get warnings when something is wrong in the future.
- Replace all instances of `#method.*` with better syntax.
=> Use intradoc links rather than #method anchors.

src/plugins/collision/broad_phase.rs
- At around 13,000 colliders, none of which could collide with each other, I was seeing the broad phase alone taking ~20ms
- Wanting to bring it down to something more manageable, I experimented with various ways to potentially speed up the broad phase
- Believe it or not, the biggest gain I found was to simply break out of the loop sooner
- Move the `aabb2.mins.x > aabb1.maxs.x` check that can break out of the loop to the very top, before the inactive/layer checks
- This resulted in the 13,000 colliders going from taking ~20ms to just ~2ms
- I've understood this to be caused by the layer check causing the `continue` to be triggered, preventing the loop from ever hitting the early `break` branch
=> Move x comparison in broad phase up to early-out as soon as possible

src/plugins/setup/mod.rs, src/plugins/setup/time.rs
Fixes #223.
In the migration to Bevy 0.12, the time resources were changed to use Bevy's unified `Time` APIs. However, the fixed timestep broke, as it now runs once every frame with the same timestep, which causes frame rate dependent behavior where bodies seem to move faster at higher frame rates.
Add a `max_delta_overstep` property to `TimestepMode::Fixed` that limits how much time can be added to the accumulated `overstep` during a single frame. This is mostly equivalent to getting the elapsed time using `Time<Virtual>` with some `max_delta`, but for now, it's nice to keep the `Time<Physics>` behavior separate from the virtual clock.
=> Fix fixed timestep using `max_delta_overstep`

src/plugins/solver.rs
If a Name component exists, of course.
Also logs the starting position of colliding items at debug level.
Makes it easier to identify which entities may be spawned too close.
Added `Option<Name>` to the query in `penetration_constraints()`, and use that in the logged message.
=> Include entity Name in logged warning for overlapping colliders

src/plugins/setup/mod.rs
This runs many times each second and overwhelms other debug logging. Lowering to `trace!` means it's still there when useful to debug the physics plugins (`RUST_LOG="warn,bevy_xpbd_3d=trace" cargo run`) but doesn't spam the console otherwise.
Make debug log less spammy. :)
Change from `debug!()` to `trace!()` for the spammiest messages. :)
=> Reduce verbosity of schedule log messages to trace

src/plugins/prepare.rs, src/plugins/spatial_query/mod.rs, src/tests.rs
Adding bevy_xpbd to a schedule should not cause it to report order ambiguities. This is essential for deterministic rollback to work.
Add a test that tries to add PhysicsPlugins to a deterministic schedule, and update it once. If the schedule has ambiguitiy errors, it will panic.
False positives should be marked with `system.ambiguous_with`.
Order the init shapecast systems in prepare explicitly before the other systems, to resolve the current ambiguities.
---
- Fixed system order ambiguities
=> Fix system order ambiguities, and add a test for it

src/components/mod.rs
I was confused about what mass my bodies were getting by default. And from the docs, it seemed like they shouldn't have any.
Fixed the incorrect documentation
=> docs: Fix incorrect docs for mass component auto-initialization

src/plugins/setup/mod.rs
If user systems were added to any of the physics schedules (e.g. `PostProcessCollisions`) before `PhysicsPlugins` are added, the schedules would be replaced when adding `PhysicsPlugins`, effectively ignoring the user's system.
```rust
app
.add_systems(PostProcessColllisions, filter_collisions)
.add_plugins(PhysicsPlugins);
```
Solve it by using `edit_schedule` instead of `add_schedule`.
- Systems can now be added to `PostProcessSchedule`, `PhysicsScedule` and `SubstepSchedule` before adding `PhysicsPlugins`
=> Don't overwrite schedules when adding plugin

src/plugins/solver.rs
Currently, local contact normals are only rotated by the rotation of each body, but the rotation of child colliders is not taken into account. This causes collision stability issues and incorrect behavior when child colliders are rotated.
For example, with the code below, the cube falls through the ground as reported by `@mbreac` on the Bevy Discord:
```rust
fn main() {
App::new()
.add_plugins((DefaultPlugins, PhysicsPlugins::default()))
.add_systems(Startup, setup)
.run();
}
fn setup(
mut commands: Commands,
mut materials: ResMut<Assets<StandardMaterial>>,
mut meshes: ResMut<Assets<Mesh>>,
) {
// floor
commands
.spawn(PbrBundle {
mesh: meshes.add(shape::Box::new(4., 0.3, 4.).into()),
material: materials.add(Color::WHITE.into()),
..default()
})
.insert(RigidBody::Static) …
```
=> Take child collider rotation into account for contact normals

src/plugins/debug/mod.rs
Fixes #240.
Currently, when the physics debug rendering is disabled, mesh visibility (configured by `hide_meshes`) is not updated because the system responsible for the updates is behind a run condition.
Move `change_mesh_visibility` out of the run condition so that it works even when debug rendering is disabled.
=> Fix mesh visibility not being reset when physics debug is disabled

src/plugins/collision/broad_phase.rs
Currently, collisions between multiple child colliders of the same rigidbody are ignored by the solver. However:
- Collision events are generated for such cases.
- All such collisions are processed in the narrow phase, which has a large performance impact in projects that rely heavily on child colliders.
Preferably all such collisions should be filtered out earlier, in the broad phase, to avoid both of these issues.
- Keep the `ColliderParent` of a collider in `AabbIntervals` in the broad phase.
- Ignore a collision if the `ColliderParent` of two entities is equal.
- Collisions between children of the same rigidbody are no longer reported in contact events and are no longer processed in the narrow phase.
=> Filter collisions between children of the same rigidbody in broad phase

src/components/collider.rs, src/plugins/prepare.rs
fixes #248 
adds a variant `ComputedCollider::TriMeshWithFlags` that allows for generation of Colliders with flags using AsyncCollider.
=> Added variant TriMeshWithFlags to ComputedCollider, fix #248

src/plugins/sync.rs
The run condition for running `position_to_transform` is preventing `update_collider_scale` from running when it is disabled. Collider scaling should still always work.
Move the run condition so that it doesn't affect collider scaling.
=> Allow collider scaling with `position_to_transform` disabled

src/components/world_queries.rs, src/plugins/solver.rs, src/plugins/sync.rs, src/utils.rs
Fixes #246 and #244.
If we consider `AccumulatedTranslation` to represent the translation of the center of mass (instead of the position),
it's only necessary to account for the center of mass offset when applying the translation. Since we already have access to the original position and translation, computing the change in `Position` based on the change in center of mass position and rotation is straightforward.
Usages of `AccumulatedTranslation` that assumed it refers to a translation applied directly to `Position` had to be updated. Fortunately, `AccumulatedTranslation` is often accessed through `RigidBodyQuery::current_position`, so not many changes were needed.
There's no measurable performance impact when testing in my game with hundreds of child colliders and profiling with Tracy …
=> Fix rotations when center of mass is offset

src/constraints/joints/prismatic.rs
Using Vector::Y here doesn't work if axis1 is parallel with Y (or close to it due to precision issues).
=> Use any_orthogonal_vector to get orthogonal vector

src/plugins/debug/mod.rs
Fixes #260.
Currently, the size of the debug-rendered yellow dot visualizing the center of mass in the middle of a body's axes is hard-coded. This is annoying and confusing when working at different scales than the assumed default scale.
Derive the radius of the dot based on the average of the debug rendered rigid body axis lengths.
=> Scale debug rendering of center of mass dot by axis lengths

src/plugins/setup/mod.rs
insert_resource always overwrites the existing resource, so if you insert your own physics time. e.g. for fixed timestep before adding PhysicsPlugins, you would still get non-fixed time.
init_resource only adds the resource if it isn't already added, using the default constructor, which should otherwise have the same behavior as before.
=> Don't overwrite `Time<Physics>` when `PhysicsPlugins` are added

src/components/collider.rs
In order to roll back collider components (or restore save games), they need to implement `MapEntitities`.
Implement `MapEntities` for `ColliderParent` and `CollidingEntities`.
=> Implement `MapEntities` for collider components

src/components/collider.rs
`Collider::set_shape` only updates the unscaled version of the collider. The scaled version incorrectly remains unchanged.
Update the scaled version as well.
=> Apply scale in `Collider::set_shape`

src/plugins/collision/broad_phase.rs
Currently, the broad phase determines whether a body is inactive just by checking if the position or rotation has changed. If a static body is moved, it will unnecessarily check collisions against other static bodies. This can cause performance issues with e.g. floating point worlds where all entities are frequently moved.
Also check whether the body is static in the `update_aabb_intervals` system.
=> Ignore static-static collisions in broad phase

src/plugins/integrator.rs
In #272, the integrator was changed to update rotation only if `delta.w != 0.0`. However, in some cases, x, y, or z can be non-zero even if w is zero, like with `AngularVelocity(Vec3::X)`, and in those cases the rotation would incorrectly be ignored.
Make the condition stricter by also checking if x, y, and z are 0. Based on a quick test, this should also keep change detection working, which is what #272 was trying to address.
=> Fix rotation change detection in integrator

src/plugins/collision/broad_phase.rs
#283 had an oversight where it required colliders to have a `RigidBody` for AABBs to be updated. It also didn't handle child colliders.
Use the `ColliderParent` to get the (optional) `RigidBody` of the entity the collider is attached to.
=> Fix static body handling in `update_aabb_intervals`

crates/bevy_xpbd_3d/Cargo.toml, crates/bevy_xpbd_3d/examples/distance_joint_3d.rs, src/constraints/joints/distance.rs, src/constraints/joints/mod.rs
Currently, the distance limits in `DistanceJoint` don't actually work, and it always just uses the rest length instead.
If distance limits are specified, use them, otherwise use the rest length. Eventually, we should probably just remove the rest length in favor of only the min/max distance limits.
I also managed to clean up *and* optimize the limit handling a bit by making `DistanceLimit::compute_correction` return the correction direction and magnitude separately.
=> Fix `DistanceJoint` distance limits

crates/bevy_xpbd_2d/examples/sensor.rs, src/plugins/collision/narrow_phase.rs
Fixes #264 
https://github.com/Jondolf/bevy_xpbd/assets/9356891/b77c9eba-aa21-474c-bec0-1cc3f5f24800
> This section is optional. If this was a trivial fix, or has no externally-visible impact, you can delete this section.
- Added example
- Added collision preservation logic
5 tests are failing when I run them, but they fail without my changes so idk
<details><summary>Details</summary>
```
Running unittests ../../src/lib.rs (target\debug\deps\bevy_xpbd_3d-f7a1d1ec81464a89.exe)
running 10 tests
test components::tests::coefficient_combine_works ... ok
test components::tests::restitution_clamping_works ... ok
test components::world_queries::tests::mass_properties_add_assign_works ... ok
test components::world_queries::tests::mass_properties_sub_assign_works ... ok
test …
```
=> Preserve collisions between inactive entities, add sensor example

src/plugins/collision/contact_reporting.rs
- Describe the objective or issue this PR addresses.
- If you're fixing a specific issue, say "Fixes #X".
Just a quick correction on the documentation for documentation on `ContactReportingPlugin`. The docs here use the deprecated `.iter()` function from `EventReader`. I searched the content of the repo and it looks like this is the only time the deprecated function is called.
- Describe the solution used to achieve the objective above.
Change `.iter()` to `.read()`.
=> docs: use the read function for iterating over events

src/plugins/collision/contact_reporting.rs
- Describe the objective or issue this PR addresses.
- If you're fixing a specific issue, say "Fixes #X".
There are a few more examples in the documentation that I missed with my last PR of using the deprecated `.iter` function of `EventReader`.
- Describe the solution used to achieve the objective above.
I've changed the sample to use `.read` instead.
=> docs: corrects other outdated calls to .iter

src/plugins/setup/mod.rs
There are currently two issues that cause `Time` to be inconsistent, even with a fixed timestep:
1. After the substepping loop, the `Time` resource is always set to `Time<Virtual>`. However, the `PhysicsSchedule` is still running. This means that systems running after substeps but before the end of the physics schedule will have a variable `Time`.
2. After the `PhysicsSchedule`, `Time` is set to `Time<Virtual>`. This means that if physics is run in `FixedUpdate`, the fixed timestep will be overwritten by `Time<Virtual>`.
1. Set `Time` to `Time<Physics>` instead. The physics schedule will later set it to the default clock.
2. Set `Time` to the clock that was used before the `PhysicsSchedule`.
=> Fix `Time` inconsistency after substepping loop

src/components/collider.rs
Looking through the code it appears we have a round cuboid available from Parry but are missing the function to create it. Rounded cuboids are handy for several things though in my case it's providing a smooth tunnel edge for couched players entering tunnels and also offering slight "just missed it" jump handling.
I reviewed the cubiod functions and SharedShapes to determine the round_cubiod pattern. Not sure if I've missed some things and happy to accept any changes or add tests and docs as needed.
Added
2d: `Collider::round_cuboid(x_length: Scalar, y_length: Scalar, border_radius: Scalar)`
3d: `Collider::round_cuboid(x_length: Scalar, y_length: Scalar, z_length: Scalar, border_radius: Scalar)`
=> Adding Collider::round_cuboid

src/lib.rs, src/plugins/setup/time.rs
#211 has a solution for camera jitter when following physics entities: https://github.com/Jondolf/bevy_xpbd/issues/211#issuecomment-1789342920
This is such a common issue that it should at least be mentioned in the FAQ.
Add solution for camera following jitter to documentation FAQ.
=> Add section about camera following jitter to FAQ

src/plugins/debug/configuration.rs, src/plugins/debug/mod.rs, src/plugins/debug/renderer.rs
Currently, only contact points can be debug rendered. It'd be useful to support rendering contact normals.
Add contact normal debug rendering. The old `contact_color` and similar configuration options have been renamed like `contact_point_color`.
I also fixed the arrow gizmo that previously sometimes rendered the tip with an incorrect orientation. When Bevy 0.13 is released, it can be replaced with the built-in arrow gizmo.
---
- Renamed `PhysicsDebugConfig` properties and methods like `contact_foo` to `contact_point_foo`
- Added corresponding `contact_normal_foo` properties and methods
- Removed `With<Collider>` filter from `debug_render_contacts`
- Fixed arrow gizmo
- Change `PhysicsDebugConfig` properties and methods like `contact_foo` to `contact_point_foo`
=> Debug render contact normals

crates/bevy_xpbd_3d/examples/cast_ray_predicate.rs, src/plugins/collision/mod.rs, src/plugins/spatial_query/pipeline.rs, src/plugins/spatial_query/system_param.rs
As I was writing a xpbd backend for bevy_mod_picking, I found that a ray cast with a predicate was missing to implement the functionality efficiently. 
I was inspired by the predicate from bevy_rapier: https://github.com/dimforge/bevy_rapier/blob/c6bcce4695d596a7a9c8e91748d4dbb3d31f6d13/src/pipeline/query_filter.rs#L12
- Implement a ray cast function with the support for a predicate function to filter the colliders
- Added support for a predicate starting at SpatialQuery and down the pipeline
- I added a small (and fun to play with) example to illustrate one possible use case
- I chose not to change existing functionality. Therefore there is some code duplication in QueryPipelineAsCompositeShapeWithPredicate. This could be unified by introducing an Option in QueryPipelineAsCompositeShape, …
=> Implement cast_ray_predicate to allow filtering the colliders with a function

src/plugins/collision/broad_phase.rs, src/plugins/sync.rs
On the main branch, collisions between colliders without a `RigidBody` component are currently not detected. This is because some queries are overly strict and require components that only rigid bodies have.
Make some components in queries optional in order to fix non-rigidbody colliders.
=> Fix colliders without `RigidBody` not working

src/components/mod.rs, src/components/rotation.rs, src/plugins/spatial_query/mod.rs
- Fixes #288 
- If no Rotation and Position is available, fall back to GlobalTransform
- I've added a `From<GlobalTransform>` and `From<&GlobalTransform>` to `Position` as well as a `From<&GlobalTransform>` to `Rotation`. as a `From<GlobalTransform>` already existed.
I tested the updated `update_ray_caster_positions` system in my personal project, and it fixed the problem for me. I currently can't test the `update_shape_caster_positions` but as it is basically the same changes, i'd be surprised if it wouldn't work.
as this is my first time contributing to this crate, i'm not sure if the code is what is expected.
=> fix raycast does not follow entity transform without rigidbody

src/constraints/penetration.rs, src/lib.rs, src/plugins/collision/contact_query.rs, src/plugins/collision/mod.rs, src/plugins/collision/narrow_phase.rs, src/plugins/debug/configuration.rs, src/plugins/debug/mod.rs, src/plugins/setup/mod.rs, src/plugins/solver.rs
Having access to contact impulses can be very useful for several tasks, like implementing destructable objects or determining how much damage a hit should deal. Currently, however, this is not really possible.
There should be a way to access contact impulses.
Add properties for normal and tangent (i.e. friction) impulses to `ContactData`. These are computed for `PenetrationConstraint`s in the constraint solver and stored in `Collisions` in the new `SubstepSet::StoreImpulses` system set.
The impulses can be accessed in `Collision` events or using the `Collisions` resource. Note that the impulses in `Colision` events are currently *only from the last substep*.
Impulses are stored instead of forces for a few reasons:
- It's more efficient internally, as it skips some operations
- Impulses …
=> Store impulses in contacts and refactor contact data

crates/bevy_xpbd_3d/examples/cast_ray_predicate.rs, src/components/layers.rs, src/plugins/spatial_query/query_filter.rs
Fixes #322 (among other things).
Improve and simplify the API used for `CollisionLayers` and `SpatialQueryFilter`.
Add a `LayerMask` struct that stores a bitmask used for collision layers. The `groups` and `masks` properties have also been renamed to `memberships` and `filters`, because "groups" and "layers" sound like the same thing, and "masks" might be confusing since it's a single bitmask (just like groups/memberships). The new naming is also what Rapier uses.
A `LayerMask` can be created from a `u32`, a type implementing `PhysicsLayer`, or an array of layers. `CollisionLayers::new` now takes `impl Into<LayerMask>`. All of the following work:
```rust
let layers = CollisionLayers::new(0b00010, 0b0111);
let layers = CollisionLayers::new(GameLayer::Player, [GameLayer::Enemy, …
```
=> Rework layers

src/plugins/collision/collider/parry.rs, src/plugins/spatial_query/system_param.rs
Fixes #245.
The docs have a few errors and outdated method names.
- Use `TransformBundle` instead of `Transform` in `Collider` docs to make positioning actually work
- Fix `cast_ray_predicate` docs calling the wrong method and using non-existent variables
- Fix `compute_aabb` -> `aabb`
=> Fix doc examples

src/plugins/spatial_query/shape_caster.rs
As reported by `@nezuo` on the Bevy Discord, the documentation for the `time_of_impact` in `ShapeHits` is inaccurate and contradictory.
> How long the shape travelled before the initial hit, i.e. the distance between the origin and the point of intersection.
These are two separate things: "the distance between the origin and the point of intersection" implies that it corresponds to the blue line, but in reality it is the orange line.
Clarify the doc comment and remove the incorrect part:
> The time of impact (TOI), or how long the shape travelled before the initial hit.
=> Fix time of impact description in `ShapeHits`

src/plugins/collision/collider/parry/mod.rs
Fixes #342.
The 2D heightfield only has a scalar `scale` argument instead of allowing different scaling along each coordinate axis. The docs are also incorrect.
Take a `Vec2` instead of a scalar value for the 2D `Collider::heightfield` and fix the heightfield docs.
---
The 2D `Collider::heightfield` method now takes a `Vec2` scale instead of a single float. This way, it now supports non-uniform scaling.
```rust
// Before
let collider = Collider::heightfield(heights, 2.0);
// After
let collider = Collider::heightfield(heights, Vec2::new(2.0, 2.0));
```
=> Fix 2D heightfield scale and docs

src/plugins/spatial_query/mod.rs
Fix 3D `ShapeCaster` global rotation. Currently, shape and parent rotation are adding its `Quat` instead of multiplying.
Multiply the rotations instead of adding.
-----
https://github.com/Jondolf/bevy_xpbd/assets/4665205/7aa92bec-fa62-4810-b518-945fd9896859
=> Fix 3D ShapeCaster global_rotation

crates/examples_common_2d/Cargo.toml, crates/examples_common_2d/src/lib.rs, crates/examples_common_3d/Cargo.toml, crates/examples_common_3d/src/lib.rs
- Enable using the PhysicsDebugPlugin in examples with `cargo run --example cubes --release --features examples_common_3d/use-debug-plugin`
- I added a feature to examples_common_[2d,3d] that adds the physics debug plugin
=> Add feature to examples_common to enable PhysicsDebugPlugin

crates/bevy_xpbd_derive/Cargo.toml, crates/bevy_xpbd_derive/src/lib.rs
Improve errors in the `PhysicsLayer` derive macro
Instead of panicking, we can instead return a `compile_error!` macro. This removes the "proc-macro panicked" message and also allows us to specify a span (location in the code) for the error.
I'm thinking of also adding a `nightly` feature which uses the unstable diagnostic API for even better errors.
---
- Improved errors in the `PhysicsLayer` derive macro
=> Use `compile_error!` macro instead of panicking in `PhysicsLayer` derive macro

src/plugins/prepare.rs
The `prepare/init_transforms` system has multiple issues:
- Returns early when `!config.transform_to_position` from loop so only the first item of the query is being processed
- ~~`is_rb: Has<C>` is redundant in the presence of `Added<C>`~~
- changed `is_rb: Has<C>` to `is_rigid_body: Has<RigidBody>`
- Where there is `Position` and/or `Rotation` and `config.transform_to_position` but no `Transform`, no new `Transform` is added
- When there is no `Position` and/or `Rotation` and  `config.transform_to_position` the `new_position`/`new_rotation` ignore the current transform and only take the global transform
Added a test to cover this system and fixed the found issues. Also refactored out some of the deep nesting in the implementation. Note that the test does not yet cover `GlobalTransform`s …
=> various fixes in the `prepare/init_transforms` system

src/math/double.rs, src/math/single.rs, src/plugins/collision/collider/parry/mod.rs, src/plugins/collision/collider/parry/primitives2d.rs, src/plugins/debug/gizmos.rs
Currently, regular polygons don't have their own collider shape. Instead, the `From<RegularPolygon>` implementation computes the convex hull and creates a convex polygon from that. This may not be the most efficient approach however, as some computations can be simpler and more efficient if the polygon is known to be regular.
This PR adds a custom shape implementation for the 2D `RegularPolygon` primitive.
Add a `RegularPolygonWrapper` type that is used as the internal representation for the custom regular polygon shape. The custom shape uses the ID `2`.
---
If you had a custom Parry shape using the ID `2`, you might need to change it, because the ID is used for regular polygons.
=> Implement `RegularPolygon` colliders with a custom shape

src/plugins/collision/collider_backend.rs
As noticed by @Occuros on Discord, collider scale is currently applied only at the end of each physics frame. As a result, there is always one-frame delay before scale is applied.
Apply collider scale before physics instead of afterwards. I also added query filters to only iterate over entities with changed transforms.
=> Apply collider scale before physics instead of afterwards

src/plugins/collision/collider_backend.rs
As noted by @janhohenheim on Discord, if you have a hierarchy like this:
- Root entity
- `RigidBody` and `Collider`
- ...
The root entity's scale is not correctly propagated to the rigid body and its colliders.
Take the scales of the ancestors into account for child rigid bodies in the `propagate_collider_transforms` system.
=> Fix collider scale for child rigid bodies

Cargo.toml, crates/bevy_xpbd_2d/Cargo.toml, crates/bevy_xpbd_3d/Cargo.toml
Glam 0.27 support was [merged and released in 0.3.26](https://github.com/dimforge/nalgebra/pull/1390) so I think this should work with the crates.io version now. 
The tests don't all pass, but that doesn't look like it's related to nalgebra, just the bevy update.
=> Update bevy-0.14 branch to crates.io release of nalgebra 

src/components/mass_properties.rs, src/plugins/collision/collider/backend.rs, src/plugins/collision/collider/mod.rs
Similar to #355 by @yrns, but without special casing `ColliderDensity` defaults, and implemented with observers.
Sensor colliders currently contribute to the mass properties of rigid bodies. This differs from most peoples' expectations, and is also different from many existing engines such as Godot and Unity. Sensor colliders should have no impact on the physics simulation.
- When the `Sensor` component is added to an entity, remove the collider's contribution on the rigid body's mass properties.
- When the `Sensor` component is removed from an entity, add the collider's mass properties to the rigid body's mass properties.
There is a test to make sure that the mass properties of a rigid body are updated accordingly when the `Sensor` component is first added and then removed from a …
=> Make sensors not contribute to mass properties

src/constraints/joints/fixed.rs, src/constraints/joints/prismatic.rs, src/constraints/joints/revolute.rs
Fixes #229.
Fixed joints and prismatic joints appear to have the wrong sign for the angular correction. This can cause bad instability issues, as seen in #229.
Additionally, the code for the revolute joint angle limit is very wrong and only works for specific limits and axes.
- Negate the angular correction sign for the fixed joint and prismatic joint. The XPBD paper doesn't have this, so we might have a wrong sign elsewhere, but that can be investigated in a follow-up.
- Fix the revolute joint angle limit by computing the axes properly.
Before:
https://github.com/Jondolf/bevy_xpbd/assets/57632562/f4d5dc62-3b02-490d-b63d-e9355f21d0a4
After:
https://github.com/Jondolf/bevy_xpbd/assets/57632562/3469d880-ee03-466f-a2c5-11eff4f1c786
Before: (see how the limit gets stuck after a few rotations) …
=> Fix angular corrections for some 3D joints

crates/avian3d/examples/custom_constraint.rs, src/collision/collider/backend.rs, src/debug_render/mod.rs, src/dynamics/solver/joints/distance.rs, src/dynamics/solver/joints/fixed.rs, src/dynamics/solver/joints/mod.rs, src/dynamics/solver/joints/prismatic.rs, src/dynamics/solver/joints/revolute.rs, src/dynamics/solver/joints/spherical.rs, src/dynamics/solver/xpbd/angular_constraint.rs, src/dynamics/solver/xpbd/mod.rs, src/dynamics/solver/xpbd/positional_constraint.rs, src/lib.rs
The joint code has a lot of ugly parts:
- 2D joints are implemented as just 3D joints with Z as the rotation axis instead of being "true" 2D.
- `SphericalJoint` exists in 2D even though it doesn't really work since it's a 3D joint.
- Lagrange update computation often unnecessarily takes unit gradients. The gradients aren't needed if they have unit length, and in our case they do.
- Some variable and method names are very vague, like `delta_q` or `p` instead of `rotation_difference` and `impulse`.
- The 3D `AngleLimit::compute_correction` method has no comments or explanations for the angle magic it does.
Fix the issues :)
I also did some other small cleanup and fixed some intra-doc links.
---
- `SphericalJoint` no longer exists in 2D. Use `RevoluteJoint` instead.
- `AngleLimit` properties …
=> Clean up and refactor joint logic

src/plugins/sync/mod.rs
#380 significantly sped up transform propagation by reducing unnecessary work with physics entity ancestor markers. However, it also seems to have caused a severe bug: `GlobalTransform` is not updated for rigid bodies that have children that all are *not* physics entities.
The problem lies in `propagate_transforms_physics`, which *only* iterates through entities that are marked as ancestors of rigid bodies or colliders. Rigid bodies that have children but no physics entity descendants are just skipped.
In `sync_simple_transforms_physics`, don't only iterate through rigid bodies with no children, but also through rigid bodies that have children but are *not* ancestors of other physics entities.
=> Fix `GlobalTransform` updates for entities with non-physics children

crates/avian2d/Cargo.toml, crates/avian2d/examples/ccd.rs, src/collision/broad_phase.rs, src/collision/collider/backend.rs, src/dynamics/ccd/mod.rs, src/dynamics/mod.rs, src/lib.rs
#385 added speculative collision, a form of Continuous Collision Detection (CCD) with the goal of preventing tunneling. However, it isn't perfect; speculative collision can sometimes cause ghost collisions, and it can miss collisions against objects spinning at very high speeds.
Another form of CCD is swept CCD, which sweeps colliders from their previous positions to the current ones, and moves the bodies to the time of impact if a hit was found. This can be more reliable than speculative collision, and can act as a sort of safety net when you want to ensure that an object has no tunneling, at the cost of being more expensive and causing "time loss" where bodies appear to stop momentarily as they are brought back in time.
Both forms of CCD are valuable and should exist. They can also be …
=> Implement sweep-based CCD

crates/avian2d/examples/dynamic_character_2d/main.rs, crates/avian2d/examples/kinematic_character_2d/main.rs, crates/avian2d/examples/sensor.rs, crates/avian3d/examples/dynamic_character_3d/main.rs, crates/avian3d/examples/kinematic_character_3d/main.rs, src/collision/collider/backend.rs, src/collision/collider/constructor.rs, src/collision/collider/parry/mod.rs, src/collision/collider/parry/primitives2d.rs, src/collision/collider/parry/primitives3d.rs, src/dynamics/ccd/mod.rs, src/dynamics/rigid_body/locked_axes.rs, src/dynamics/rigid_body/mod.rs, src/dynamics/rigid_body/world_query.rs
The `new` constructors for Bevy's `Cylinder`, `Capsule`, and `Cone` shapes take a radius first, and a height second.
```rust
Capsule::new(radius, height)
```
However, our collider constructors use the opposite order:
```rust
Collider::capsule(height, radius)
```
The reason for this is that I originally followed Parry's argument ordering, and Bevy's primitive shapes were added afterwards with a different ordering.
This is a very unfortunate inconsistency and can easily lead to confusion. Even though changing this will lead to very clear breakage for a large number of applications, I believe it is important that we align ourselves with Bevy here.
Make the argument ordering for all collider constructors match Bevy.
---
To match Bevy's `Cylinder`, `Capsule`, and `Cone`, the order of arguments …
=> Fix inconsistency between collider constructors and Bevy's primitives

src/collision/collider/backend.rs, src/collision/collider/mod.rs, src/collision/collider/parry/mod.rs, src/collision/collider/world_query.rs, src/collision/narrow_phase.rs, src/dynamics/ccd/mod.rs, src/dynamics/solver/contact/mod.rs, src/type_registration.rs
Collisions for thin objects such as triangle meshes can sometimes have stability and performance issues, especially when dynamically colliding against other thin objects.
- Infinitely thin objects are more prone to numerical issues and tunneling. Two trimeshes colliding against each other can easily get stuck in an intersecting state or have other collision issues.
- Collision algorithms for intersecting objects are typically more expensive than for the non-intersecting state. Trimesh collisions can be very expensive if the trimesh has dense geometry.
To allow users to mitigate these issues when necessary, engines such as Rapier and Bullet provide a *collision margin* or *contact skin* that forces the solver to maintain an artificial separation distance between objects. It can be thought …
=> Implement collision margin

src/collision/broad_phase.rs, src/collision/collider/constructor.rs, src/collision/collider/mod.rs, src/collision/collider/parry/mod.rs, src/collision/contact_query.rs, src/collision/layers.rs, src/collision/narrow_phase.rs, src/debug_render/configuration.rs, src/dynamics/integrator/mod.rs, src/dynamics/rigid_body/forces.rs, src/dynamics/rigid_body/locked_axes.rs, src/dynamics/rigid_body/mass_properties.rs, src/dynamics/rigid_body/mod.rs, src/dynamics/sleeping/mod.rs, src/dynamics/solver/joints/distance.rs, src/dynamics/solver/joints/fixed.rs, src/dynamics/solver/joints/mod.rs, src/dynamics/solver/joints/prismatic.rs, src/dynamics/solver/joints/revolute.rs, src/dynamics/solver/joints/spherical.rs, src/position.rs, src/schedule/mod.rs, src/schedule/time.rs, src/spatial_query/pipeline.rs, src/spatial_query/query_filter.rs, src/spatial_query/ray_caster.rs, src/spatial_query/shape_caster.rs, src/type_registration.rs
Updated version of #351.
A lot of types are missing `ReflectSerialize` and `ReflectDeserialize` implementations with the `serialize` feature enabled, and several types are also not registered in the `TypeRegistry`.
Add `#[cfg_attr(feature = "serialize", reflect(Serialize, Deserialize)]` for types that were missing it, and register more types in the `PhysicsTypeRegistrationPlugin`. I also fixed and added some other derives, including removing `Component` from `CoefficientCombine`.
---
`CoefficientCombine` is no longer a component. It was never supposed to be one, and did nothing on an entity anyways.
=> Add `#[reflect(Serialize, Deserialize)]` and register more types

.github/workflows/ci.yml, src/debug_render/gizmos.rs, src/debug_render/mod.rs
The debug rendering is using some incorrect math types when the `f64` feature is enabled, causing compilation to fail.
Fix the types and add `debug-plugin` to CI so it hopefully catches this in the future.
=> Fix `f64` support with `debug-plugin` feature

src/collision/collider/backend.rs, src/collision/collider/constructor.rs, src/collision/collider/parry/mod.rs
Avian 0.1.0 introduced a regression where `bevy_render` is now needed because `Mesh` is not optional. It should be feature-gated behind `collider-from-mesh`.
Put all mentions of `Mesh` behind the `collider-from-mesh` feature.
=> Fix `Mesh` not being optional

src/dynamics/solver/contact/mod.rs
Fixes #407.
The solver rework caused a regression where contact normals didn't take the rotation of child colliders into account in the contact solver, leading to buggy collisions.
Transform the normal correctly. Also remove unnecessary transformations of the normals of the individual contact points in the contact solver, as they are not used anywhere.
=> Fix solver contact normal for rotated child colliders

src/sync/ancestor_marker.rs
Fix the issue where `remove_ancestor_markers` crashes if an entity has children moved or removed, and then is despawned before `remove_ancestor_markers`  is run.
When remove component from an entity, just check if that entity exists first.
=> Fix remove ancestor markers crash

src/collision/collider/parry/mod.rs
- `collision::collider::parry::TrimeshFlag` is missing parry's `TriMeshFlags::FIX_INTERNAL_EDGES`.
- This PR copy-pastes the implementation from parry (with `1 << 7` changed to `0b1000_0000` for consistency).
---
- Added parry's `FIX_INTERNAL_EDGES` to TrimeshFlags, which fixes some collisions from edges on flat surfaces.
=> Add parry's TriMeshFlags::FIX_INTERNAL_EDGES to avian's TrimeshFlags

src/collision/narrow_phase.rs
The `custom_collider` example is currently broken on some runs, because contact constraints are cleared by every instance of `generate_constraints`. If there are multiple collision backends at the same time, they can overwrite each other's results.
Clear contact constraints in a separate system that always only has one instance.
=> Fix contact constraints being cleared many times with many backends

src/collision/collider/backend.rs, src/collision/collider/hierarchy.rs, src/sync/ancestor_marker.rs, src/tests.rs
Avian 0.1.0 introduced a regression where `HierarchyPlugin` and `ColliderHierarchyPlugin` are needed for colliders to function, as `ColliderParent` was only inserted by `ColliderHierarchyPlugin`. Hierarchies shouldn't be necessary.
Update `ColliderParent` for colliders that are on the `RigidBody` entity in the `ColliderBackendPlugin`, and change panics to warnings when using `ColliderHierarchyPlugin` without `HierarchyPlugin`.
=> Make `HierarchyPlugin` optional

src/dynamics/integrator/mod.rs, src/dynamics/sleeping/mod.rs, src/prepare.rs
Currently, sleeping and waking is handled after physics. This leads to a one frame delay before bodies are woken up by things like velocity changes or applied external forces. It can even cause `ExternalImpulse` to do nothing, because the body is only woken up by the time the impulse should've already been applied and cleared.
Run sleeping logic before physics. User changes are detected by comparing component change ticks to a `LastPhysicsTick` resource. This refactor also lets us get rid of the `PhysicsChangeTicks` component, which was previously stored and updated for all physics entities.
`PhysicsStepSet::Sleeping` now technically doesn't have much sleeping logic anymore, but that can be reworked in a follow-up.
=> Handle sleeping logic before physics

src/dynamics/rigid_body/mod.rs
Fixes #463 
Default implemented with 1.0f32
=> [+]Avian(Backend) - GravityScale::Default changed to 1.0f32

src/collision/collider/hierarchy.rs, src/collision/collider/parry/mod.rs, src/collision/mod.rs, src/dynamics/rigid_body/forces.rs, src/dynamics/solver/xpbd/mod.rs, src/prepare.rs, src/schedule/mod.rs, src/spatial_query/mod.rs, src/spatial_query/pipeline.rs, src/spatial_query/system_param.rs, src/sync/mod.rs
Fixes #287 and part of #471.
Scale is currently not propagated correctly for colliders if the rigid body is not the root entity. Additionally, negative scale is prohibited for child colliders: scale is clamped to be greater than zero.
Fix scale propagation and allow negative scale.
Note that mirroring is *not* handled properly for child colliders and some shapes yet. That will be fixed later.
=> Fix collider scale propagation issues

src/collision/collider/backend.rs, src/collision/collider/hierarchy.rs, src/collision/collider/mod.rs, src/collision/contact_query.rs, src/collision/feature_id.rs, src/collision/mod.rs, src/dynamics/ccd/mod.rs, src/lib.rs, src/spatial_query/mod.rs, src/type_registration.rs
Avian caused a regression from bevy_xpbd that makes the engine require `parry-f32` or `parry-f64`. Avian should be usable without Parry.
- Add our own `PackedFeatureId` type (API matches Parry to avoid breaking changes for now)
- Put collider constructor logic behind `default-collider` feature flags
- Put swept CCD systems behind `parry-f32`/`parry-f64`
- We could *maybe* traitify this and make swept CCD work for custom colliders, but currently it has some logic that depends heavily on Parry shapes, so for now it is just disabled without Parry.
=> Fix usage without Parry

src/dynamics/integrator/semi_implicit_euler.rs
Fixes #474.
The angular locked axes are applied to the inertia instead of the inverse inertia in gyroscopic torque computations introduced in #420, causing incorrect behavior.
Apply the locked axes correctly.
=> Fix angular locked axes in gyroscopic torque computation

src/collision/collider/backend.rs, src/collision/collider/hierarchy.rs, src/dynamics/ccd/mod.rs, src/lib.rs, src/prepare.rs, src/spatial_query/mod.rs, src/spatial_query/ray_caster.rs, src/spatial_query/shape_caster.rs, src/sync/mod.rs
Fixes #475.
Missing components for rigid bodies, colliders, etc. are currently added at specific points in the physics shedule. This means that the world is momentarily in an invalid state before those systems are run, which can even lead to confusing crashes when using methods like `query.single()` for queries that expect those components to exist.
Use component hooks for initializing missing components with minimal delay. This also meaningfully simplifies scheduling.
When Bevy gets required components (Soon™), those could be used instead.
Using hooks appears to be as fast if not *faster* than the old initialization systems.
---
`PrepareSet::PreInit` has been renamed to `PrepareSet::First`, and `PrepareSet::InitRigidBodies`, `PrepareSet::InitColliders`, and …
=> Use hooks for component initialization

src/spatial_query/pipeline.rs
-  `cast_ray` already has a sister function called `cast_ray_predicate` that returns the first hit that satisfies a predicate. The other casts do not.
- Implement them. Note that I set the internal implementations of the non-predicate versions to use the predicate to reduce code duplication. The predicate does not introduce an extra branch since we already have an `if` for the filter in place, so this should be equivalent in performance.
---
> This section is optional. If this was a trivial fix, or has no externally-visible impact, you can delete this section.
- Added
- `cast_ray` already has a sister function called `cast_ray_predicate` that returns the first hit that satisfies a predicate. Now, the other cast function have a similar analogue:
- Added `cast_ray_predicate` for `cast_ray` …
=> Add predicate variants to all casts

crates/avian2d/examples/collision_layers.rs, crates/avian_derive/Cargo.toml, crates/avian_derive/src/lib.rs, src/collision/layers.rs
#476 changed collision layers to reserve the first bit for a default layer. However, for enums implementing `PhysicsLayer`, the default layer is rather implicit and potentially footgunny.
The default layer should ideally be more explicit.
Change `PhysicsLayer` to require `Default` to be implemented. The proc macro orders the variants such that the layer set as the default is always the first bit.
Note that `Default` *must* currently be derived instead of implemented manually, as the macro can only access the default variant if the `#[default]` attribute exists. An error is emitted if `#[default]` does not exist. If someone knows a way to make it work with the manual impl, let me know or consider opening a PR!
I also added documentation for the `PhysicsLayer` macro, and improved error …
=> Make `PhysicsLayer` require a `#[default]` variant

src/dynamics/integrator/mod.rs
The docs for `IntegratorPlugin::new` mention the wrong default schedule.
Fix the docs.
=> Fix default schedule in `IntegratorPlugin::new` docs

crates/avian2d/Cargo.toml, crates/avian3d/Cargo.toml
While depending on Avian's `main` branch, running `cargo doc --all-features` fails on my crate when including a serialize feature
Fix bitflags not being serializable when serializing. Ideally, the CI should catch this.
=> Fix missing feature flag

src/dynamics/sleeping/mod.rs
- With a large number of colliding bodies, I was seeing `wake_on_collision_ended` use almost as much time as `run_substep_schedule` in some cases
- I narrowed the slowness down to evaluation of [this if condition](https://github.com/Jondolf/avian/blob/2f83cc15bd804ad82ecd7e080e337d052d1c3472/src/dynamics/sleeping/mod.rs#L280-L285)
- Evaluating this once takes around 3μs on my laptop which isn't a huge deal on its own, but when there's 2500 colliders it started to add up to multiple milliseconds
- In `wake_on_collision_ended`, skip the body of the first for loop (over `sleeping`) if the following both hold true:
- The body does not already have a `Sleeping` component
- TimeSleeping is 0.0
I believe this is ok because the side-effects of that loop is to remove the `Sleeping` component and …
=> Optimize `wake_on_collision_ended` when large number of collisions are occurring

src/sync/mod.rs
Fixes #516.
Rotation is currently updated incorrectly in 3D by `transform_to_position`. It uses addition and subtraction instead of multiplication for quaternions. This causes clear desync between `Transform` rotation and `Rotation` when `SyncConfig::position_to_transform` is `false` and the `Transform` is changed:
https://github.com/user-attachments/assets/5b51480e-6f55-4317-9ed1-ec02f9c4d640
Fix the rotation update. We can also remove the normalization, because individual quaternion multiplications should remain normalized, assuming the inputs are normalized (and there aren't too many successive rotations).
Now, the desync is fixed:
https://github.com/user-attachments/assets/8922832f-21b4-4ed9-947d-bd4b77786647
=> Fix 3D rotation update in `transform_to_position`

src/dynamics/solver/joints/mod.rs, src/dynamics/solver/xpbd/mod.rs
Make disabling joints possible.
I added `DisableJoint` and added the `Without<DisableJoint>` filter on the query.
In discord Jondolf had used the name `JointDisabled`; however, I thought the verb form `DisableJoint` was my preference. But this is not a strong opinion. If there are other past tense components, then I'm happy to have it either way.
I added derives for copy, clone, reflect, and serialize but these were added to follow suit rather than for a good reason of my own. 
One could set the compliance to a large number. But what large number? And why bother computing when one would prefer disabling?
---
- Joints can be disabled with the `DisableJoint` component.
=> Make disabling joints possible.

src/collision/mod.rs
It can be tricky to match and handle all of an entity's collision states in a single event loop. I routinely find myself writing code like this:
```
for Collision(contacts)in events.read() {
let started = contacts.during_current_frame && !contacts.during_previous_frame;
let stopped = !contacts.during_current_frame && contacts.during_previous_frame;
if started {
} else if stopped {
}
```
Add `Contacts::collision_started` and `Contacts::collision_stopped` to more conveniently check these conditions.
- Added `Contacts::collision_started` and `Contacts::collision_stopped` for more conveniently checking if a collision just started or stopped.
=> Add convenience methods for determining if collisions are starting or stopping

src/collision/collider/backend.rs, src/dynamics/integrator/mod.rs, src/dynamics/mod.rs, src/dynamics/rigid_body/mass_properties/components.rs, src/dynamics/rigid_body/mass_properties/mod.rs, src/dynamics/rigid_body/mass_properties/world_query.rs, src/dynamics/rigid_body/mod.rs, src/lib.rs, src/prepare.rs
Logic related to mass properties is currently a bit scattered around (`PreparePlugin`, `ColliderBackendPlugin`...), and there is also no way to opt out of automatic updating of mass properties. It would be nice to encapsulate this logic inside a single plugin, especially as we rework mass properties (#499) and add more APIs and functionality for working with mass.
This also contributes to the goal of removing `PreparePlugin`, which is currently full of various miscallaneous and unrelated logic.
Add a `MassPropertyPlugin`. It updates mass properties of rigid bodies when colliders are added or removed, or when their `ColliderMassProperties` are updated. It also logs warnings for invalid mass properties, and updates `GlobalAngularInertia`.
Previously, the logic for updating mass properties …
=> Add `MassPropertyPlugin`

src/spatial_query/system_param.rs
- Doc tests in `src/spatial_query/system_param.rs` fail
- Fix doc tests
=> Fix spatial query doc tests

src/dynamics/rigid_body/mod.rs
`Deref` & `DerefMut` trait is missing for 2D `AngularVelocity`.
added the missing deref and derefMut traits.
---
-  added deref and derefMut traits to `AngularVelocity` for avian2d.
=> Added missing deref and derefMut trait to AngularVelocity in 2D

src/collision/mod.rs
Sometimes when getting information about collisions, you might not want all contacts, but rather the one with the largest penetration.
Add `find_deepest_contact` helpers for `Contacts` and `ContactManifold`.
=> Add `find_deepest_contact` for `Contacts` and `ContactManifold`

src/collision/mod.rs
Sometimes it can be useful to flip contact data, for example when you want to guarantee that `contact.point1` is always the point on the desired entity when iterating over its contacts.
Add `flip` and `flipped` helpers for `ContactData` and `SingleContact`.
=> Add helpers for `ContactData` and `SingleContact` to flip contact data

src/lib.rs
The plugin table for the docs of `PhysicsPlugins` mentions `PhysicsDebugPlugin` as a plugin that is added by default, but it isn't. `PhysicsPickingPlugin` on the other hand isn't mentioned at all.
Add a separate table for additional plugins.
=> Fix plugin table

src/collision/collider/backend.rs, src/collision/collider/world_query.rs, src/collision/narrow_phase.rs, src/debug_render/gizmos.rs, src/dynamics/rigid_body/mass_properties/world_query.rs, src/dynamics/rigid_body/world_query.rs, src/spatial_query/pipeline.rs, src/spatial_query/system_param.rs
Rust 1.83.0 was just released, and CI is complaining because of new lints, mainly for ellided lifetimes.
Fix lints!
=> Fix new Rust 1.83.0 lints

crates/avian2d/Cargo.toml, crates/avian2d/examples/dynamic_character_2d/plugin.rs, crates/avian2d/examples/kinematic_character_2d/plugin.rs, crates/avian3d/Cargo.toml, crates/avian3d/examples/dynamic_character_3d/plugin.rs, crates/avian3d/examples/kinematic_character_3d/plugin.rs, crates/benches_common_2d/Cargo.toml, crates/benches_common_3d/Cargo.toml, crates/examples_common_2d/Cargo.toml, crates/examples_common_3d/Cargo.toml
The full 0.15 release has a few breaking changes from the release candidate.
Fix them! Also changed `bevy_mod_debugdump` to use the main branch instead of the 0.15 PR's branch, since it has now been updated.
=> Migrate from Bevy 0.15 RC to full 0.15

src/sync/mod.rs
Fixes #522.
The order of multiplication for the quaternions in `transform_to_position` seems to be wrong, which can cause desync between `Transform` rotation and `Rotation` when `position_to_transform` in `SyncConfig` is `false`.
Flip the order of multiplication where relevant.
There is now no desync:
https://github.com/user-attachments/assets/9b6f8ae0-4cdd-4b54-8490-726d24932a84
=> Fix rotation multiplication order in `transform_to_position`

src/collision/collider/parry/mod.rs
Fixes #368.
Many users create 2D triangle colliders with clockwise orientation. However, this produces a collider that doesn't work, as Parry seems to require conterclockwise orientation.
Check the orientation in `Collider::triangle`, and reverse it if necessary. If the orientation is known to be counterclockwise, `Collider::triangle_unchecked` can be used instead.
=> Make sure `Collider::triangle` is oriented CCW

src/dynamics/integrator/mod.rs, src/dynamics/rigid_body/mod.rs
Closes #410.
Sometimes, it can be useful to limit the maximum speeds of bodies. This can also be useful for preventing explosive behavior when there is instability.
Add `MaxLinearSpeed` and `MaxAngularSpeed` components. Global configuration could be added too in the future.
=> Add `MaxLinearSpeed` and `MaxAngularSpeed`

crates/avian3d/examples/cubes.rs, src/collision/narrow_phase.rs, src/dynamics/integrator/mod.rs, src/dynamics/rigid_body/mod.rs, src/dynamics/sleeping/mod.rs, src/dynamics/solver/mod.rs, src/dynamics/solver/xpbd/mod.rs, src/lib.rs, src/type_registration.rs
Fixes part of #436.
A pretty common user request is to be able to temporarily disable rigid bodies without removing them from the world. This can be done by removing `RigidBody`, but this loses the type of rigid body, makes queries a bit more annoying, and can involve somewhat expensive clean-up.
In the absence of general-purpose component disabling in Bevy, it would be useful to have a `RigidBodyDisabled` marker that can be used to temporarily remove a body from the simulation.
Add a `RigidBodyDisabled` marker component. It disables velocity, forces, contact response, and attached joints. It does *not* disable collision detection or spatial queries for attached colliders however; that should be handled with a separate `ColliderDisabled` component in a follow-up.
=> Add `RigidBodyDisabled`

src/collision/broad_phase.rs, src/collision/collider/mod.rs, src/collision/narrow_phase.rs, src/dynamics/sleeping/mod.rs, src/lib.rs, src/spatial_query/system_param.rs
Closes #436.
Follow-up to #536.
Avian already supports disabling rigid bodies (#536) and joints (#519). The missing piece is disabling colliders!
Add a `ColliderDisabled` component for temporarily disabling collision detection for colliders and removing them from spatial queries.
For now, I decided *not* to prevent disabled colliders from contributing to mass properties of rigid bodies, since the primary purpose of the component is to temporarily disable collision detection, and I think it would be unexpected if it affected the behavior of the rigid body in any other way.
=> Add `ColliderDisabled`

src/collision/collider/mod.rs, src/dynamics/rigid_body/mod.rs, src/dynamics/solver/joints/mod.rs, src/lib.rs
- Improve `JointDisabled` docs
- Mention `JointDisabled` in crate docs
- Remove unnecessary derives, improve consistency
=> Tweak disabling docs

src/collision/collider/backend.rs, src/dynamics/ccd/mod.rs, src/dynamics/integrator/semi_implicit_euler.rs, src/dynamics/solver/xpbd/angular_constraint.rs, src/dynamics/solver/xpbd/positional_constraint.rs, src/position.rs, src/tests/determinism_2d.rs
Currently, only 3D rotation is renormalized after position integration. However, 2D rotation can also become denormalized over time, sometimes causing crashes with `debug_assertions`.
Add `fast_renormalize` for 2D `Rotation` and renormalize 2D rotations after position integration.
I also renamed the 3D `Rotation::renormalize` method to `fast_renormalize`, and made it return the value instead of mutating `self`, to match Bevy 0.15.
---
The 3D `Rotation::renormalize` method has been renamed to `fast_renormalize`, and it returns the value instead of mutating `self`. This was changed to match Bevy 0.15.
=> Renormalize rotation in 2D integration and clean up `renormalize`

crates/avian2d/Cargo.toml
Closes #591.
- `avian2d` no longer fails to build when `serialize` is enabled and various bevy features are disabled.
=> Fix missing `bevy_render/serialize` dependency.

src/collision/collider/parry/mod.rs, src/collision/collider/parry/primitives2d.rs, src/debug_render/gizmos.rs
Fixes #595.
Currently, `EllipseWrapper` and `RegularPolygonWrapper` are not public, so you cannot access their information at runtime for colliders.
Make them public, and rename them to `EllipseColliderShape` and `RegularPolygonColliderShape` for clarity.
=> Expose `EllipseColliderShape` and `RegularPolygonColliderShape`

README.md, src/collision/collider/mod.rs, src/collision/collider/parry/mod.rs, src/dynamics/ccd/mod.rs, src/dynamics/rigid_body/mass_properties/mod.rs, src/dynamics/rigid_body/mod.rs, src/dynamics/rigid_body/physics_material.rs, src/dynamics/solver/joints/mod.rs, src/lib.rs
This is just a polish pass to clarify and clean up some parts of the documentation and make things more discoverable.
=> Documentation improvements

README.md, crates/avian2d/Cargo.toml, crates/avian2d/examples/custom_collider.rs, crates/avian3d/Cargo.toml, crates/avian_derive/Cargo.toml, crates/avian_derive/src/lib.rs, src/lib.rs, src/picking/mod.rs, src/spatial_query/mod.rs, src/type_registration.rs
Update version numbers and do final release preparation.
=> Release 0.2.0

src/dynamics/rigid_body/mass_properties/components/mod.rs
- This prevents a panic that can occur if an entity with one of the NoAuto components is despawned.
- Fixes #607 
This solution to the problem just uses the non-panicking versions of retrieving an entity from the world and inserting a component in the on_remove_no_auto_mass_property function that runs when the component is removed. 
I think an argument could be made that this silently hides an issue of code trying to operate on an entity that no longer exists or that the on_remove shouldn't fire if it's happening because an entity is being despawned.
=> Prevent panic when despawning entities with NoAuto components

src/dynamics/solver/contact/tangent_part.rs
3D friction currently has a bug that causes objects with a small angular inertia to twist and jitter strangely on the ground:
https://github.com/user-attachments/assets/8cc4aa25-808a-4899-b8a4-5079a48c4be1
(reproduction by occuros <3)
The problem was caused by an angular inertia term being included *twice* for a part of the effective inverse mass computation for 3D friction. With that fixed, resting contacts are much more stable even with small mass properties:
https://github.com/user-attachments/assets/c2d829b3-bcf5-4c8e-997d-57614e741e1d
=> Fix effective inverse mass computation for 3D friction

src/lib.rs, src/sync/mod.rs
Some places still mention `PostUpdate` as the default schedule for physics, even though it should be `FixedPostUpdate` now.
Fix them.
=> Fix outdated mentions of the default schedule

crates/avian2d/examples/one_way_platform_2d.rs, src/collision/broad_phase.rs, src/collision/collider/world_query.rs, src/collision/hooks.rs, src/collision/mod.rs, src/collision/narrow_phase.rs, src/dynamics/ccd/mod.rs, src/lib.rs, src/schedule/mod.rs
Closes #150.
Advanced contact scenarios often require filtering or modifying contacts with custom logic. Use cases include:
- One-way platforms
- Conveyor belts
- Non-uniform friction and restitution for terrain
Physics engines typically handle this with *hooks* or *callbacks* that are called during specific parts of the simulation loop. For example:
- Box2D: `b2CustomFilterFcn()` and `b2PreSolveFcn` (see [docs](https://box2d.org/documentation/md_simulation.html#autotoc_md97))
- Rapier: `PhysicsHooks` trait with `filter_contact_pair`/`filter_intersection_pair` and `modify_solver_contacts` (see [docs](https://rapier.rs/docs/user_guides/bevy_plugin/advanced_collision_detection#physics-hooks))
- Jolt: `ContactListener` with `OnContactValidate`, `OnContactAdded`, `OnContactPersisted`, and …
=> Collision Hooks

src/tests/determinism_2d.rs
CI is failing because Bevy 0.15.1 had a breaking change that reverted the default behavior for missing system parameters back to panicking (even though patch releases shouldn't have any meaningful breaking changes...) and one of our tests was relying on the behavior in 0.15.0.
Add the relevant plugins to fix the panic.
=> Fix test after 0.15.1 breakage

src/schedule/mod.rs
Fixes #619.
When pausing physics, the `PhysicsSchedule` can still run even though the delta time is zero. This can cause simulation problems and sometimes even results in values becoming NaN or infinite due to division by zero.
This is a regression from 0.1, which handled scheduling differently and did not run physics with a delta time of zero.
Don't run the `PhysicsSchedule` if the delta time is zero.
=> Fix physics being run with zero delta time

src/position.rs
Fixes #617.
`sin` and `cos` are the wrong way around for our `From<Rotation>` implementation for Bevy's `Rot2`. This is currently used for center of mass updates in 2D, and the wrong order causes the center of mass vector to be perpendicular to what it should be.
Fix the order.
=> Fix `From<Rotation>` implementation for `Rot2`

crates/avian2d/examples/one_way_platform_2d.rs, src/collision/collider/backend.rs, src/collision/narrow_phase.rs, src/dynamics/mod.rs, src/dynamics/rigid_body/world_query.rs, src/dynamics/sleeping/mod.rs, src/dynamics/solver/xpbd/mod.rs
Avian 0.2.0 has a regression from 0.1 where the `TimeSleeping` component is required, but it is only added automatically (as a required component) if the `SleepingPlugin` is enabled. This means that disabling the `SleepingPlugin` breaks physics.
Make `TimeSleeping` properly optional for rigid bodies.
I also added a `WakeUpBody` `Command` to clean up some logic and abstract away resetting `TimeSleeping`.
=> Fix `SleepingPlugin` not being optional and add `WakeUpBody` command

crates/avian_derive/Cargo.toml, crates/avian_derive/src/lib.rs
The Avian macro crate uses `proc-macro-error`, which is [unmaintained](https://rustsec.org/advisories/RUSTSEC-2024-0370), this also leads to an outdated version of `syn` in the dependency tree.
Replace `proc-macro-error` with `proc-macro-error2`.
=> Fix use of unmaintaned crate proc-macro-error

src/spatial_query/pipeline.rs
The docs say that the ray/shape casts will stop on the first instance where the predicate returns false, but it seems like the opposite is the case.
Maybe it would be good to add a unit test to confirm this.
=> Fix SpatialPipeline with_predicate docs

src/dynamics/rigid_body/forces.rs, src/dynamics/rigid_body/mod.rs
Fixes #626
Make avian3d::dynamics::rigid_body::forces public
---
avian3d::dynamics::rigid_body::forces is now public
=> Make avian3d::dynamics::rigid_body::forces public

src/dynamics/rigid_body/mod.rs
Linear velocity components don't currently specify units, and the code examples don't consider delta time for acceleration.
This PR improves some of the documentation to clear up what the components represent.
Mention units, and improve code examples.
=> Improve docs for velocity components

src/collision/narrow_phase.rs
Fixes #533
There is currently a bug where despawning an entity as soon as a collision starts never ends up removing the collision, meaning that `CollisionEnded` is not sent and the despawned entity is not removed from `CollidingEntities`. This is caused by collision states not being updated correctly for despawns.
Reset the collision states when an entity is missing such that the collision will be treated as ended.
Note that the way this is handled will change substantially when we implement a contact graph and rework contact management, but regardless, I think it is important to have a fix for it now as it is a serious bug.
=> Fix collisions not being cleared for immediately despawned entities

crates/avian3d/examples/picking.rs, src/lib.rs, src/picking/mod.rs
=> Introduce `PhysicsPickingFilter`

src/dynamics/rigid_body/mass_properties/components/mod.rs
Some mass property helpers like `Mass::from_shape` are currently gated behind the `default-collider` feature and Parry, even though they don't need these features anymore.
Remove the feature gates.
=> Remove unnecessary `cfg_attr` from `from_shape` mass helpers

src/collision/collider/constructor.rs
#476 changed `CollisionLayers` to use one membership (the first layer) and all filters by default. However, `ColliderConstructorHierarchy` is still using the old default!
Use `CollisionLayers::default()` (one membership, all filters) by default for `ColliderConstructorHierarchy`.
---
`ColliderConstructorHierarchy` now defaults to one membership (the first layer) and all filters for the `CollisionLayers` of generated colliders. This is consistent with how `CollisionLayers` already works normally.
=> Fix the default layers used by `ColliderConstructorHierarchy`

crates/avian2d/Cargo.toml, crates/avian2d/examples/custom_collider.rs, crates/avian2d/examples/kinematic_character_2d/plugin.rs, crates/avian2d/examples/one_way_platform_2d.rs, crates/avian3d/Cargo.toml, crates/avian3d/examples/kinematic_character_3d/plugin.rs, src/collision/contact_query.rs, src/collision/mod.rs, src/collision/narrow_phase.rs, src/debug_render/mod.rs, src/dynamics/solver/contact/mod.rs, src/dynamics/solver/mod.rs, src/lib.rs, src/tests/determinism_2d.rs
A lot of Avian's current contact types store some redundant data, aren't properly optimized, and aren't explicit enough about what they represent.
This PR is a clean-up pass to make the types a bit smaller and clearer.
- Replace `total_normal_impulse` property with `total_normal_impulse`, `total_normal_impulse_magnitude`, and `max_normal_impulse` helpers
- Deprecate `total_normal_force` helper
- You can just divide by the substep timestep
- Remove `total_tangent_impulse` property and `total_friction_force` helper
- These could previously technically be wrong/misleading, since each contact point can have a different tangent direction, especially in 3D, and they can also change between substeps. The tangent impulse magnitudes of each individual point can still be accessed.
- Rename …
=> Improved contact types

crates/avian2d/examples/custom_collider.rs, crates/avian3d/Cargo.toml, crates/avian3d/examples/conveyor_belt.rs, src/collision/contact_query.rs, src/collision/mod.rs, src/collision/narrow_phase.rs, src/dynamics/rigid_body/physics_material.rs, src/dynamics/solver/contact/mod.rs, src/dynamics/solver/contact/tangent_part.rs, src/dynamics/solver/mod.rs
Follow-up to #610.
Now that we have contact modification hooks, we should add support for modifying the surface properties of contacts. This can enable use cases like conveyor belts or non-uniform friction and restitution for different parts of a mesh.
Add `friction`, `restitution`, and `tangent_speed`/`tangent_velocity` properties to `ContactManifold`. These are copied over for each `ContactConstraint`.
> [!NOTE]
> **Why not have a hook for modifying `ContactConstraint` directly instead?**
>
> While we could technically do this right now, once we have wide SIMD constraints, `ContactConstraint` will also have its own SIMD version that is not as user-friendly and depends on feature flags. Providing hooks for modifying that is not very viable, and it would not be good for UX. Splitting …
=> Per-manifold material properties and tangent velocity

src/collision/collider/backend.rs, src/collision/collider/mod.rs
#527 used a read-only `UnsafeWorldCell` for the initialization of `ColliderAabb` in an `on_add` hook for `Collider`. However, it uses methods that provide mutable access, which is unsafe and panics with debug assertions.
Remove the whole AABB initialization logic and use of `unsafe`. Having it didn't make sense since the initial positions are likely wrong anyway.
`ColliderAabb` is now explicitly specified to be `ColliderAabb::INVALID` until the first physics update.
=> Remove unsafe `ColliderAabb` initialization

src/collision/collider/backend.rs, src/collision/collider/collider_hierarchy/mod.rs, src/collision/collider/collider_hierarchy/plugin.rs
Fixes #676.
#671 changed the `ColliderParent` component to a `ColliderOf` relationship. Because Bevy does not normally allow relationships to point to their own entities, this required a partial manual implementation of the `Relationship` trait. However, I left the default `on_replace` implementation, which (as it turns out) panics if the target entity does not exist, which is possible when despawning an entity and the relationship points to itself.
Manually implement `on_replace` in a non-panicking way. Also replace some panicking uses of `remove` with `try_remove`.
Ideally this would be fixed by Bevy allowing self-relationships though.
=> Fix panic caused by despawning entity with `ColliderOf`

src/collision/collider/collider_hierarchy/plugin.rs
When a `RigidBody` is added to a hierarchy that already has existing colliders, the `ColliderOf` relationships aren't updated correctly.
Fix `ColliderOf` updates to also consider newly added rigid bodies.
=> Fix `ColliderOf` updates when a rigid body is added in the hierarchy

crates/avian2d/examples/one_way_platform_2d.rs, crates/avian3d/examples/conveyor_belt.rs, crates/avian3d/examples/custom_broad_phase.rs, src/collision/broad_phase.rs, src/collision/contact_types/contact_graph.rs, src/collision/contact_types/mod.rs, src/collision/contact_types/system_param.rs, src/collision/hooks.rs, src/collision/narrow_phase/system_param.rs, src/debug_render/mod.rs, src/diagnostics/ui.rs, src/dynamics/solver/contact/mod.rs, src/lib.rs
Especially after #683, we use the term "contact pair" a lot. However, the contact pair type is called `Contacts`. This name is very ambiguous: does it represent all contacts in the world, all contacts between two entities, contacts belonging to a specific contact surface, or something else?
Rename `Contacts` to `ContactPair`. It much more accurately describes what the type represents: contact data for a pair of entities that may be in contact. This is also the name used by Rapier.
---
`Contacts` has been renamed to `ContactPair`.
=> Rename `Contacts` to `ContactPair`

src/collision/narrow_phase/system_param.rs, src/data_structures/bit_vec.rs
Fixes #687.
The narrow phase is currently initializing the thread-local contact status bit vectors with a block count of zero. This means that for the first tick, contact status changes might not be tracked correctly. The bitwise OR to combine the bit vectors also currently panics with debug assertions enabled, because the sizes of the vectors don't match.
Initialize thread-local contact status bit vectors with the correct block count.
I also improved the error message for the debug assertion in `BitVec::or`.
=> Create thread-local contact status bit vecs with correct block count

crates/avian2d/Cargo.toml, crates/avian3d/Cargo.toml, crates/benches_common_2d/Cargo.toml, crates/benches_common_3d/Cargo.toml, crates/examples_common_2d/Cargo.toml, crates/examples_common_3d/Cargo.toml, src/collision/collider/backend.rs, src/collision/collider/collider_transform/plugin.rs, src/dynamics/rigid_body/mass_properties/mod.rs, src/prepare.rs, src/spatial_query/mod.rs, src/sync/ancestor_marker.rs, src/sync/mod.rs
- Address changes to Bevy's `ChildOf` structure to fix compilation from bevyengine/bevy/pull/18672
- Use tuple struct pattern and `parent()` method for access to parent entity
=> Refactor ChildOf from named to tuple struct

src/collision/broad_phase.rs, src/collision/collider/backend.rs, src/collision/collider/parry/mod.rs, src/collision/collider/world_query.rs, src/collision/layers.rs, src/collision/narrow_phase/mod.rs, src/collision/narrow_phase/system_param.rs, src/spatial_query/pipeline.rs, src/spatial_query/system_param.rs, src/tests/determinism_2d.rs
Contact pair removal currently has some issues.
1. Contact pair removal is done using the `EdgeIndex` directly, but removing an edge can move the indices around (due to `swap_remove`), which can sometimes result in incorrect pair removal if many pairs are removed at once.
2. Changing `CollisionLayers` doesn't update existing contact pairs.
3. When a collider is removed or disabled, `CollisionEnded` is sent even for non-touching contact pairs.
Fix the things!
For problem 2, I just made the narrow phase always check if the `CollisionLayers` match for now. Ideally, we'd handle this with fine-grained change detection instead.
`CollisionLayers` is now also a required component for colliders. This avoids extra branching and is perhaps more semantically accurate; colliders can only belong to …
=> Fix contact pair removal bugs

src/collision/broad_phase.rs, src/collision/narrow_phase/mod.rs
Bevy 0.16 introduces entity disabling via the `Disabled` component. We need to handle this for the contact graph and broad phase.
Remove disabled entities from the contact graph using observers, and add re-enabled collider entities to the broad phase.
=> Handle entity disabling properly

src/spatial_query/pipeline.rs, src/spatial_query/ray_caster.rs, src/spatial_query/shape_caster.rs, src/spatial_query/system_param.rs
The `SpatialQueryPipeline` currently has some egregious overhead for scenes with a large number of entities. It allocates an `EntityHashMap` with *all* colliders (`Arc`ed) and some other data, from scratch, *every frame*. Even worse, it allocates QBVH nodes for all entities up to the largest collider `Entity` index. For a scene with 999,999 non-physics entities and one collider, it seems to allocate a *million* QBVH nodes every frame. This produces profiles like this:
Yikes!
Just store QBVH proxies in a `Vec`, and use those vec indices rather than `Entity` indices for QBVH building. This also lets us replace a bunch of hashmap lookups with vector indexing, get rid of some `Entity` conversions, and avoid table scans for `Added<Collider>`.
This is still kind of a duct-tape fix. We should …
=> Reduce `SpatialQueryPipeline` overhead

README.md, src/collision/collision_events.rs, src/collision/mod.rs, src/collision/narrow_phase/mod.rs, src/schedule/mod.rs
Closes #361.
Closes #481.
A common user request is to allow listening to collision events for specific entities, with an API where you don't need to check e.g. which entity is the player and which entity is an enemy like you might need to do when using `CollisionStarted` and `CollisionEnded`. The typical Bevy API for per-entity events like this is observers.
On the surface, this is a straightforward addition. However, there have historically been some challenges and open questions:
1. We don't want to trigger collision events for *every* contact. Doing so would mean that we get one buffered event and two observable events (one for each entity) per started/ended contact pair, which could add up to a decent amount of overhead.
2. Observable events shouldn't store two entities like …
=> Add observable `OnCollisionStart` and `OnCollisionEnd` events

README.md, crates/avian2d/Cargo.toml, crates/avian3d/Cargo.toml, crates/benches_common_2d/Cargo.toml, crates/benches_common_3d/Cargo.toml, crates/examples_common_2d/Cargo.toml, crates/examples_common_3d/Cargo.toml, src/diagnostics/ui.rs
Fixes #708.
Alternative to #674 and #710.
#710 updates Avian to Bevy 0.16, but doesn't update the README. Both #674 and #710 also fix an error about missing `bevy_animation` by enabling the `animation` feature (only in 2D, so 3D is still broken) rather than removing the root problem, the unnecessary use of `Animatable` in `src/diagnostics/ui.rs`.
Update to Bevy 0.16 and replace the use of `Animatable` with manual interpolation code.
=> Update to Bevy 0.16.0

.github/workflows/ci.yml, src/collision/narrow_phase/system_param.rs, src/dynamics/solver/contact/mod.rs
Multithreaded determinism is currently broken! This is because #699 accidentally resulted in contact constraint order being non-deterministic. CI didn't catch this, because it currently doesn't use the `parallel` feature.
When the `parallel` feature is enabled, store the pair index for each `ContactConstraint`, and just sort the constraints based on these indices.
I suspect that a better approach that doesn't require sorting exists, but for now, this works as a simple hot-fix. I also tried the simple approach of returning `Vec`s from Bevy's `par_splat_map_mut`, but that would mean that we can't reuse the constraint buffers, and have to allocate from scratch every time. Either way, there's more to try and experiment with here.
Because the constraints within chunks are still largely sorted, …
=> Sort contact constraints for determinism when `parallel` feature is enabled

src/sync/ancestor_marker.rs
While despawning entities with hierarchies and RigidBody components, the following error would occur
```
Encountered an error in command <bevy_ecs::system::commands::entity_command::remove<avian3d::sync::ancestor_marker::AncestorMarker<avian3d::collision::collider::backend::ColliderMarker>>::{{closure}} as bevy_ecs::error::command_handling::CommandWithEntity<core::result::Result<(), bevy_ecs::world::error::EntityMutableFetchError>>>::with_entity::{{closure}}: The entity with ID 727v1 was despawned by forks/bevy/crates/bevy_scene/src/scene.rs:112:46
```
This was because the removal command gets queued instantly due to running in an observer on collider removal but the command gets deferred until after the entity no longer exists.
changed removal of AncestorMarker to use try_remove to avoid …
=> Use try_remove to avoid errors on AncestorMarker removal

src/collision/collision_events.rs, src/collision/narrow_phase/mod.rs
#704 added observable `OnCollisionStart` and `OnCollisionEnd` events. However, they only provide the collider entity, and that is also just behind a nameless tuple field. It could be nicer to use named fields and also provide the rigid body entity.
Use named `collider` and `rigid_body` fields. `rigid_body` is `None` if the collider is not attached to a rigid body.
=> Include rigid body entity in `OnCollisionStart` and `OnCollisionEnd`

crates/avian2d/examples/dynamic_character_2d/plugin.rs, crates/avian2d/examples/kinematic_character_2d/plugin.rs, crates/avian3d/examples/dynamic_character_3d/plugin.rs, crates/avian3d/examples/kinematic_character_3d/plugin.rs, src/collision/broad_phase.rs, src/collision/collider/backend.rs, src/collision/collider/collider_hierarchy/mod.rs, src/collision/collider/collider_hierarchy/plugin.rs, src/collision/collider/collider_transform/plugin.rs, src/collision/collider/world_query.rs, src/collision/collision_events.rs, src/collision/narrow_phase/mod.rs, src/collision/narrow_phase/system_param.rs, src/debug_render/mod.rs, src/dynamics/ccd/mod.rs, src/dynamics/rigid_body/mass_properties/mod.rs, src/prepare.rs
We have a lot of properties called `rigid_body`. In a lot of cases, really the relevant part is that it is just a physics "body", and the `rigid_` qualifier is largely unnecessary. Typically, it's enough to just use `body` for properties, and it can result in cleaner names.
Rename `rigid_body` to just `body` for `OnCollisionStart`, `OnCollisionEnd`, `ColliderOf`, and many internal variables and types.
Despite using `body` for a lot of property names, I think we should still probably keep the `Rigid` prefix for types such as `RigidBody`.
---
`ColliderQuery::rigid_body` has been renamed to `of` (for `ColliderOf`) and there is a new `body` helper to get the contained entity directly.
=> Rename most `rigid_body` names to `body`

crates/avian2d/examples/determinism_2d.rs, crates/avian2d/examples/kinematic_character_2d/plugin.rs, crates/avian2d/examples/one_way_platform_2d.rs, crates/avian3d/examples/conveyor_belt.rs, crates/avian3d/examples/kinematic_character_3d/plugin.rs, src/collision/broad_phase.rs, src/collision/collider/collider_hierarchy/plugin.rs, src/collision/contact_types/contact_graph.rs, src/collision/contact_types/mod.rs, src/collision/contact_types/system_param.rs, src/collision/hooks.rs, src/collision/narrow_phase/mod.rs, src/collision/narrow_phase/system_param.rs, src/debug_render/mod.rs, src/dynamics/sleeping/mod.rs, src/dynamics/solver/contact/mod.rs, src/dynamics/solver/mod.rs
Follow-up to #718.
`ContactPair` has `entity1`, `entity2`, `body_entity1`, and `body_entity2`, while `ContactConstraint` has `entity1`, `entity2`, `collider_entity1`, and `collider_entity2`. The `entity` specifiers are kind of unnecessary, and it'd be nice if the names were more consistent and `entity1` and `entity2` were more explicit about whether they are the collider or body entities.
Rename the properties such that both `ContactPair` and `ContactConstraint` have `collider1`, `collider2`, `body1`, and `body2`.
---
- `ContactPair`: The `entity1` and `entity2` properties are now `collider1` and `collider2`, and `body_entity1` and `body_entity2` are now `body1` and `body2`.
- `ContactConstraint`: The `entity1` and `entity2` properties are now `body1` and `body2`, and `collider_entity1` …
=> Rename entity properties in `ContactPair` and `ContactConstraint`

src/spatial_query/pipeline.rs
Fixes #720.
#696 accidentally regressed `SpatialQueryPipeline::shape_intersections_callback`, mixing up the order of the input shapes.
Fix the order!
=> Fix wrong shape order in `shape_intersections_callback`

src/position.rs
The doc comment for `Rotation::from_sin_cos` mentions a non-existent `glam_assert` feature (it's in Glam, not Avian).
Fix it.
=> Fix doc comment for `Rotation::from_sin_cos`

src/collision/collider/collider_transform/plugin.rs, src/prepare.rs, src/sync/mod.rs
- Replacing the Avian transform propagation functions with the ones from the Bevy engine to leverage [0.16's faster transform propagation](https://bevyengine.org/news/bevy-0-16/#faster-transform-propagation).
Replaced every instance of these systems
```
sync_simple_transforms_physics,
propagate_transforms_physics,
```
with these directly from Bevy
```
mark_dirty_trees,
propagate_parent_transforms,
sync_simple_transforms,
```
And also removed code related to sync_simple_transforms_physics and propagate_transforms_physics that are now no longer used.
I was running into a problem on my computer where having many hierarchies was causing my FPS to vary wildly, but switching to the Bevy propagation resolved it. 
Before (averaging ~20 fps with drops into the single digits)
After (averaging a …
=> Replaced Avian transform syncs with 0.16 Bevy versions

src/collision/collider/constructor.rs, src/collision/collider/parry/mod.rs
Add a method called convex_polyline to Collider. convex_polyline should be the same as convex_hull but without computing convex hull of the points.
=> Add convex_polyline for creating Collider

.github/workflows/ci.yml, src/collision/collider/constructor.rs
- Create only new caches from `main`
- Reactivate Linux builds
- Except for `collider_constructor_hierarchy_inserts_correct_configs_on_scene`, which requires the GPU for some reason
- I thought this setup would be enough, but apparently it wasn't, since `SceneInstanceReady` is never triggered:
```rust
app.add_plugins((
MinimalPlugins,
AssetPlugin::default(),
ScenePlugin,
TransformPlugin,
MeshPlugin,
GltfPlugin::default(),
ImagePlugin::default(),
PhysicsPlugins::default(),
));
```
- Use nextest for tests
- nextest cannot do doctests, so we still use `cargo test --doc` for those
- Use fixed cache keys against cache misses
- Share cache keys for lints to reduce cache size
- Remove some debug information from the builds to reduce cache size. No worries, the test error backtraces are not …
=> Improve CI performance, cache size and reactivate Linux tests

.cargo/config_ci.toml, .github/workflows/ci.yml
For the tests:
- Use dynamic linking
- Cache the dynamic libraries
- Use LLD on Windows (our bottleneck)
- Run nightly
- Activate parallel rustc frontend
I did not change the linker to `mold` on linux nor did I activate `cranelift` there because Windows is the bottleneck by *far* and those are not reliably available there.
=> Make CI faster

src/collision/collider/backend.rs, src/collision/collider/cache.rs, src/collision/collider/constructor.rs, src/collision/collider/mod.rs, src/collision/mod.rs, src/lib.rs, src/tests/mod.rs
- Creating colliders from meshes can be expensive when not just using a trimesh
- Especially convex decomps take ages
- In end-user cases, `ColliderConstructor` and `ColliderConstructorHierarchy` are *very* popular for creating colliders from meshes
- Ideally, we would have a way to cache any and all colliders, but I think caching the ones made from a mesh with these methods would already bring us 90% of the way, from a user perspective.
So, let's cache them! Intentionally leaving the cache `pub(crate)` and not `pub` so we can easily expand it without breaking anything for users.
---
- Using `ColliderConstructor` or `ColliderConstructorHierarchy` for creating colliders from meshes will now cache the collider. This is especially noticeable when creating multiple copies of a mesh with a …
=> Cache colliders created from meshes via constructors

src/dynamics/integrator/semi_implicit_euler.rs
#738 optimized gyroscopic torque. However, it also broke it! The current algorithm only uses the diagonal of the inertia tensor at the end, when it should be using the full tensor.
Use the full tensor.
Alternatively, if we represented the inertia tensor with the principal moments of inertia and an orientation, we would just apply that additional orientation. This is what Jolt does.
=> Fix gyroscopic torque

src/dynamics/integrator/mod.rs, src/dynamics/integrator/semi_implicit_euler.rs
@unpairedbracket noticed that we right-multiply rotation instead of left-multiplying it during position integration. This affects how the rotations compose and the order they are applied. While the observable difference tends to be small here, we should get it fixed!
Fix the order of multiplication.
=> Fix order of quaternion multiplication

src/collision/collision_events.rs, src/collision/narrow_phase/mod.rs
Fixes #750
Someone (me) somehow got the entities mixed up for the `body` property of the `OnCollisionStart` and `OnCollisionEnded` events. It is documented to be the body of the entity that hit `trigger.target()`, but it is in fact the body associated with the `trigger.target()` itself. Yikes!
Additionally, the `CollisionEventsEnabled` type doesn't reflect `Component` and isn't registered. This breaks scenes.
Fix `body` to be the body of the entity that hit `trigger.target()`, and reflect `Component` for `CollisionEventsEnabled`.
This is critical enough that I'll make a 0.3.1 patch release with it soon.
=> Fix `body` property of collision events and reflect `CollisionEventsEnabled` properly

src/collision/collider/parry/primitives2d.rs, src/data_structures/bit_vec.rs, src/data_structures/graph.rs, src/diagnostics/ui.rs, src/spatial_query/ray_caster.rs, src/spatial_query/shape_caster.rs
Rust introduced a new `mismatched_lifetime_syntaxes` lint that breaks CI.
Fix the warnings!
=> Fix new `mismatched_lifetime_syntaxes` lints

src/collision/collider/constructor.rs, src/collision/collider/parry/mod.rs
Allow for the creation of compound colliders through `ColliderConstructor`.
Added a new enum variant to `ColliderConstructor` and a helper impl to allow constructing the variant with a wider variety of types.
---
> Added `ColliderConstructor::Compound`
=> ColliderConstructor::Compound

Cargo.lock, src/collision/collider/backend.rs, src/collision/collider/mod.rs, src/dynamics/rigid_body/mod.rs, src/lib.rs, src/position.rs, src/prepare.rs, src/tests/determinism_2d.rs
`Position` and `Rotation` are currently not required components for physics entities, and are only inserted at the start of the physics step. This leads to unnecessary archetype moves, but also causes problems with any logic that requires accurate physics positions before this, such as AABB updates, (future) BVH insertions, and more.
Make `Position` and `Rotation` required components for `RigidBody` and `Collider`, and initialize them with the correct global values using lifecycle hooks.
`ColliderAabb` is now also initialized correctly since the correct physics positions are available right after spawn.
The initialization logic could definitely be cleaned up and optimized... but for now it's good enough, I want to unblock some other work with this :P
---
`Position`, `Rotation`, and …
=> Rework `Position` and `Rotation` initialization

src/sync/mod.rs, src/tests/determinism_2d.rs
`PreviousGlobalTransform` is currently initialized too late, causing `Transform` updates between the spawn and first physics step to be ignored.
Make `PreviousGlobalTransform` a required component (if the `SyncPlugin` is enabled) so that it's initialized at spawn.
=> Fix `PreviousGlobalTransform` initialization

src/dynamics/solver/joints/mod.rs
`DistanceLimit::compute_correction()` would return the same direction for exceeding either `min` or `max`, while the sign was attached to the correction distance. This caused a latter < epsilon check to fail. In this PR I've negated the direction and distance for `min` case, which seems to have fixed the issue. :)
=> Fix `DistanceLimit::compute_correction()` signs

src/collision/broad_phase.rs
Fixes #739.
The broad phase uses `RemovedComponents` for detecting when `Disabled` or `ColliderDisabled` is removed. However, it can miss removals in schedules with fixed time steps. To make it more robust, we should use observers instead.
Additionally, there is a bug where child colliders of static bodies are not marked as static/inactive on the first time step.
Use observers to fix the first problem, and rework initialization logic to fix the second.
=> Fix AABB interval initialization in broad phase

src/dynamics/integrator/mod.rs, src/dynamics/mod.rs, src/dynamics/rigid_body/forces/mod.rs, src/dynamics/rigid_body/forces/plugin.rs, src/dynamics/rigid_body/forces/query_data.rs, src/dynamics/rigid_body/forces/tests.rs, src/dynamics/rigid_body/mod.rs, src/dynamics/sleeping/mod.rs
#770 added a `Forces` helper `QueryData` for applying forces, impulses, and accelerations to dynamic bodies. The intent was that forces would wake up bodies by default, but this was actually not the case, as `Forces` has some components that sleeping bodies don't.
However, we should *also* have a way to allow forces not to wake up bodies. This can be important for optimization in some cases.
Rework `Forces` to wake up bodies by default when applying non-zero forces, impulses, or accelerations. Additionally, add a `ForcesItem::non_waking` method that returns a `NonWakingForcesItem`. The two force types share a `RigidBodyForces` trait and the same API, but the former wakes up bodies while the latter doesn't.
The API looks like this:
```rust
// This does not wake up the body. …
```
=> Allow `Forces` to wake or not wake up bodies

src/collision/contact_types/mod.rs, src/dynamics/solver/contact/mod.rs, src/dynamics/solver/contact/normal_part.rs, src/dynamics/solver/mod.rs
`ContactPoint` stores a `normal_impulse`. However, this is the clamped accumulated normal impulse from the last substep, used for warm starting the solver. It does *not* represent the total impulse applied across substeps and restitution, despite the ambiguous name.
As such, we are currently missing a proper way for users to determine how "strong" a contact is. Exposing this is important for numerous gameplay scenarios, like determining when a glass bottle or window should shatter, or how much damage a hit should deal.
Rename the current `ContactPoint` properties `normal_impulse` and `tangent_impulse` to `warm_start_normal_impulse` and `warm_start_tangent_impulse`, and expose a new `normal_impulse` that represents the total normal impulse applied across substeps and restitution.
Contact …
=> Expose total normal impulses, improve contact impulse APIs

crates/avian2d/examples/custom_collider.rs, src/collision/collider/parry/contact_query.rs, src/collision/contact_types/mod.rs, src/collision/narrow_phase/system_param.rs, src/debug_render/mod.rs, src/dynamics/solver/contact/normal_part.rs, src/dynamics/solver/contact/tangent_part.rs, src/dynamics/solver/mod.rs, src/tests/determinism_2d.rs
Currently, `ContacttPoint` stores a `local_point1` and `local_point2` on the surfaces of the two shapes. These are the closest points in local space.
However:
- The solver needs the world-space contact points relative to the centers of mass. The local points are not actually needed for anything, they are just the output of Parry.
- The solver should not be using the closest points for constraints. There should be a single world-space contact point that is the midpoint between the two closest points, and world-space anchors that correspond to this point.
- Users typically only need world-space values, but getting them currently requires manual transformations.
- For users, it is confusing that a `ClosestPoint` type actually stores two points, one for each shape.
We can do better! We can …
=> Expose anchors, world-space `point`, and `normal_speed` for contacts

src/dynamics/rigid_body/mass_properties/mod.rs, src/dynamics/rigid_body/mass_properties/system_param.rs
Closes #629.
`ComputedAngularInertia` updates in 3D currently invert the tensor rather than inverting the principal moments of inertia and using those to construct the matrix. This is both less efficient and has a more limited range of supported inertia values, as the determinant gets close to zero.
Invert the principal angular inertia vector instead. Testing with a cuboid, this brings the range of supported mass values from about about `1e13` to about `1e19`.
=> Improve inverse angular inertia tensor computation

src/dynamics/solver/contact/mod.rs, src/dynamics/solver/mod.rs, src/dynamics/solver/solver_body/mod.rs, src/dynamics/solver/xpbd/mod.rs
Fixes #207
Fixes #602 (maybe, no easy repro)
For a long time, Avian has had stability problems in 3D, especially with small shapes. Shapes with a small angular inertia drift and jitter on the ground even by themselves. A simple cube stack like the following with 10 cm cubes and the standard 9.81 m/s² gravity twists and just falls apart immediately.
https://github.com/user-attachments/assets/322391af-7bc9-4a9e-b626-424d4e790645
I have long suspected that it is mostly a friction problem. Turns out, it is, and in hindsight it's a pretty simple one!
Currently, Avian computes tangent directions for friction at every substep. Naively, I thought this made sense; you want to keep the tangents up-to-date, right? However, the effective mass is computed before the substepping loop using the *old* …
=> Fix 3D friction tangents and refactor constraint preparation

src/collision/collider/parry/primitives3d.rs
- While generating a navmesh for a tiny tiny scene, my AABB was surprisingly so huge that I ran out of RAM
- Actually use the user-provided `half_size` instead of just using `10_000`. Note that that approach is alright for `InfinitePlane3d`, but not `Plane3d`
- Because it seemed like the original intent, I added support for `InfinitePlane3d` using the old behavior
-----
- Implemented `IntoCollider<Collider> for InfinitePlane3d`. This allows you to call `Collider::from` with `InfinitePlane3d`. Note that the resulting collider is not infinite, but simply has a huge half size of 10000 units.
- Calling `Collider::from` with a `Plane3d` will now respect the plane's `half_size` instead of hardcoding it to 10000 units. If you depended on the old behavior, use `InfinitePlane3d` instead.
=> Fix `Plane3d` colliders ignoring half size

src/collision/contact_types/mod.rs, src/collision/narrow_phase/system_param.rs
Contact manifolds in 3D should be limited to 4 contact points. This is important for both stability and performance, especially when we implement wide SIMD contacts.
Some specific cases (some convex polyhedron collisions or possible custom shapes) can produce more than 4 points. We should have a contact pruning algorithm to get rid of these extra points.
Implement a contact pruning algorithm that chooses the optimal points based on the distance to the center of mass, the penetration depth, and the contact area. The implementation is mostly based on Jolt.
In the future, we can combine this with a manifold reduction scheme that combines manifolds that have similar normals, pruning the resulting larger manifold.
=> Contact pruning for 3D

crates/avian2d/examples/determinism_2d.rs, src/collision/contact_types/contact_graph.rs, src/collision/contact_types/system_param.rs, src/data_structures/id_pool.rs, src/data_structures/mod.rs, src/data_structures/stable_graph.rs, src/dynamics/solver/constraint_graph.rs, src/tests/determinism_2d.rs
Contact pairs maintain stable indices using the `StableUnGraph`. It marks removes nodes and edges and vacant, and uses linked lists for free node and edge lists.
This results in reusing nodes and edges in removal order. The problem is that it causes perceived determinism issues when contacts are removed: when "restarting" a scene, old freed contacts affect the order of new reused contact edges, often causing different results. This can be seen in the `determinism_2d` example; respawning the scene produces different results *unless* the contact graph is cleared.
Ideally, this should not be something users need to worry about. Respawning the same scene should produce the same results each time without clearing any caches. This PR aims to fix this by allocating freed contact IDs in a …
=> Allocate free IDs lowest-first using an `IdPool` for `StableUnGraph`

src/dynamics/solver/joint_graph/plugin.rs, src/spatial_query/pipeline.rs, src/spatial_query/shape_caster.rs
fix "temporaries freed while still in use" across a couple of function uses.
I took the approach of keeping the clones of things like `DebugName` from the `.name` function, etc and instead stored the value so it could be referenced, since the usage relies on deref coercion to go from `DebugName` to `&str`.
The examples run after this fix
=> Fix temporaries in bevy-0.17 branch

src/dynamics/solver/constraint_graph.rs, src/tests/determinism_2d.rs
Currently, static contacts are mixed with dynamic contacts starting from the second graph color. To improve tunneling prevention, it'd be better to reserve some colors just for static contacts, and to solve them last.
- Increase the `GRAPH_COLOR_COUNT` from 12 to 24
- Reserve some colors just for static contacts, and build static colors from the end to give them higher priority
In the future, we could consider using dedicated one-body contact constraints for the static colors to further optimize things.
=> Improve tunneling prevention by solving static contacts last

crates/avian2d/Cargo.toml, crates/avian3d/Cargo.toml, src/dynamics/solver/islands/mod.rs, src/dynamics/solver/joint_graph/plugin.rs, src/lib.rs
Island validation is currently enabled if `debug_assertions` are enabled. However, it can be very costly, destroying the performance of debug builds.
Validation should be behind its own feature flag.
Add a `validate` feature, and gate island validation behind it.
=> Gate island validation behind `validate` feature

Cargo.lock, crates/avian2d/Cargo.toml, crates/avian3d/Cargo.toml
The `main` branch is currently broken, because it depends on the main branches of `glam_matrix_extensions` and `bevy_heavy` without specifying a git ref, and they have already been updated to Bevy 0.17. We need to specify a git ref that uses the old versions.
Specify functional git refs for `glam_matrix_extensions` and `bevy_heavy` .
=> Fix `glam_matrix_extensions` and `bevy_heavy` commit refs

Cargo.lock, src/dynamics/rigid_body/mass_properties/mod.rs
Rigid bodies with a `ColliderConstructor` or `ColliderConstructorHierarchy` often emit a warning for invalid mass properties before the collider has actually been generated. Annoying!
Skip the warning for rigid bodies with a `ColliderConstructor` or `ColliderConstructorHierarchy`. Once the colliders have been generated, the mass is changed, which will automatically check for invalid mass again.
=> Disable mass property warning for collider constructors
