.github/workflows/ci.yml
Cargo.lock
crates/bevy_xpbd_2d/Cargo.toml
crates/bevy_xpbd_3d/Cargo.toml
crates/examples_common_2d/Cargo.toml
crates/examples_common_3d/Cargo.toml
src/constraints/penetration.rs
src/steps/solver.rs

This is the setup I use in most of my bevy plugins.
Should make reviewing PRs a bit easier.

Add basic CI setup

---

Cargo.lock
crates/bevy_xpbd_3d/Cargo.toml

Oversight when porting to Bevy 0.10

Fix incorrect nalgebra glam conversion dependency

---

src/lib.rs
src/steps/broad_phase.rs
src/steps/prepare.rs
src/steps/solver.rs
src/tests.rs

This one depends on most of my other pending PRs. You could review them one-by-one first, the this one will make more sense :)
XpbdSchedule:
XpbdSubstepSchedule:

Fix system order ambiguities

---

src/resources.rs
src/tests.rs

Depends on #14 
Spawn a rigid body with a velocity and check that it ends up roughly where we expect it to be.
Adds just a little bit of sanity checking.

Integrator integration test

---

src/bundles.rs
src/collision.rs
src/components/mod.rs
src/components/rotation.rs
src/constraints/joints/fixed.rs
src/constraints/joints/mod.rs
src/constraints/joints/prismatic.rs
src/constraints/joints/revolute.rs
src/constraints/joints/spherical.rs
src/constraints/mod.rs
src/constraints/penetration.rs
src/lib.rs
src/math/mod.rs
src/resources.rs
src/steps/broad_phase.rs
src/steps/integrator.rs
src/steps/mod.rs
src/steps/prepare.rs
src/steps/solver.rs
src/steps/sync.rs
src/utils.rs

I documented pretty much every component, bundle, resource, system, plugin, constraint, module etc. I also added some more high-level doc comments explaining the structure of the engine and the solver.
This PR just aims to add at least a bit of documentation for all public APIs. The docs will obviously change a lot as the engine grows, and I think it'd be cool to eventually have a website with more structured docs like the one rapier has.
Let me know if you find anything that's missing, incorrect or badly written, and I'll fix it :)

Document APIs

---

src/plugins/sync.rs

Rigid bodies should behave independently regardless of nesting. To avoid unrealistic behaviour, the movement of the parent shouldn't affect the child, unless they are connected by a joint or another constraint. This is already how the physics engine works, but `Transform` is local, so bodies in nested hierarchies aren't being rendered in the correct position.
This PR fixes the issue by computing the child's `Transform` based on the global positions of the child and the parent.
Note that in some cases it can be desirable to have the parent's movement also move the child. This can generally be handled manually when needed by e.g. character controllers, but it might be worth considering alternative behaviours in the future. Some engines also don't allow nested rigid bodies at all, so another …

Set `Transform` of child entities to reflect global `Pos` and `Rot`

---

src/components/locked_axes.rs
src/components/mass_properties.rs
src/components/mod.rs
src/lib.rs
src/plugins/integrator.rs
src/plugins/mod.rs
src/plugins/spatial_query/system_param.rs

- Updated for 0.2
- Added short section on server usage
- Added comparison to Rapier in FAQ
- Improved XPBD explanation a bit
- Various other small improvements

Improved docs

---

src/components/collider.rs

Adds trimesh flags for preprocessing.

Add `trimesh_with_flags` and `trimesh_from_bevy_mesh_with_flags`

---

src/components/forces.rs

Clarify that external forces and impulses are local

---

src/plugins/setup.rs

Correct time dilation for FixedUpdate schedule.

---

src/plugins/debug/mod.rs

Currently, the sleeping status is only debug rendered for colliders on the same entity as the rigid body. It should also be rendered for child colliders.
Debug render sleeping for child colliders using `ColliderParent`.

Fix sleeping debug rendering for child colliders

---

src/components/collider.rs
src/components/layers.rs
src/components/mass_properties.rs
src/components/mod.rs
src/components/rotation.rs
src/constraints/joints/mod.rs
src/constraints/mod.rs
src/lib.rs
src/plugins/collision/contact_reporting.rs
src/plugins/collision/mod.rs
src/plugins/mod.rs
src/plugins/setup.rs
src/plugins/spatial_query/query_filter.rs
src/resources.rs

This PR adds and improves ton of docs and code examples, and adds more 2D docs. This includes docs for `Position`, `Rotation`, velocity components, scheduling, `PhysicsLoop`, collision events, the structure of `Collider` docs, and much more.

Improve documentation

---

src/lib.rs

… Bevy XPBD
- Update docs: Added Character Controller recommendation for Bevy Tnua what supports Bevy XPBD.  
It works nicely out of the box.
- Updated docs at lib.rs
---

docs: Added Character Controller recommendation for Bevy Tnua what supports Bevy XPBD 

---

src/plugins/collision/broad_phase.rs

In order to snapshot `AabbIntervals`, it needs to implement `MapEntitities` 
Implement it

Implement `MapEntities` for `AabbIntervals`

---

src/components/collider.rs

Currently, `Collider` doesn't expose Parry methods like `project_point` or `cast_ray`. This requires dealing with Nalgebra types and is overall very inconvenient.
Add helper methods to `Collider`:
- `project_point`
- `distance_to_point`
- `contains_point`
- `cast_ray`
- `intersects_ray`

Add intersection and point queries to `Collider`

---

src/components/mass_properties.rs
src/components/world_queries.rs
src/lib.rs
src/plugins/collision/collider/mod.rs
src/plugins/collision/mod.rs
src/plugins/debug/gizmos.rs
src/plugins/debug/mod.rs
src/plugins/mod.rs
src/plugins/spatial_query/mod.rs
src/plugins/spatial_query/ray_caster.rs
src/tests.rs
src/utils.rs

Fixes #331 and #332.
Bevy XPBD 0.4 requires some new features, but invalid combinations produce tons of errors and no clear help.
Fix the flood of errors and add high-level compile errors that inform how to add the correct features.

Improve error handling for invalid feature combinations

---

src/plugins/debug/configuration.rs
src/plugins/spatial_query/system_param.rs

Default features failed on these. I guess CI doesn't do the `debug-plugin` or `f32` features so it didn't catch them.

Fix some doc tests

---

src/plugins/collision/collider/parry/mod.rs

See [Discord](https://discord.com/channels/691052431525675048/1124043933886976171/1252581708864294952)

Improve trimesh docs

---

src/sync/ancestor_marker.rs
src/type_registration.rs

Fixes #460.
Add `#[reflect(Component)]` for `AncestorMarker` and register the type.

Add `#[reflect(Component)]` for `AncestorMarker` and register the type

---

src/collision/collider/mod.rs
src/collision/contact_reporting.rs
src/collision/narrow_phase.rs
src/dynamics/rigid_body/mass_properties/mod.rs
src/spatial_query/mod.rs
src/spatial_query/ray_caster.rs
src/spatial_query/shape_caster.rs
src/spatial_query/system_param.rs

- Using `Debug` on `Entity` in log messages looks weird
- Switch to `Display` where possible

Use entity Display in messages instead of Debug

---

src/collision/narrow_phase.rs

- Overlap warnings are annoying
- Yeet

Fix overlap warnings: yeet edition

---

.github/workflows/ci.yml
README.md
crates/avian2d/examples/interpolation.rs
src/dynamics/solver/mod.rs
src/dynamics/solver/schedule.rs
src/lib.rs

Some doc links are currently broken. CI should catch this!
Add `cargo doc` to CI and fix doc links. Also fixed some heading capitalization inconsistency.

Add `cargo doc` to CI and fix doc links

---

crates/avian2d/Cargo.toml
crates/avian2d/examples/one_way_platform_2d.rs
crates/avian3d/Cargo.toml
crates/avian3d/examples/conveyor_belt.rs
crates/benches_common_2d/Cargo.toml
crates/benches_common_3d/Cargo.toml
crates/examples_common_2d/Cargo.toml
crates/examples_common_3d/Cargo.toml
src/diagnostics/ui.rs
src/picking/mod.rs

Bevy 0.16.0-rc.2 was released, and it has some breaking changes. We need to update!
Update to Bevy 0.16.0-rc.2.

Update to Bevy 0.16.0-rc.2

---

src/type_registration.rs

- Some types were not registered
- Registered `PreSolveRotation` and `GlobalAngularInertia`

Register some types

---

src/collision/collider/constructor.rs
src/collision/contact_types/contact_graph.rs
src/data_structures/sparse_secondary_map.rs
src/utils.rs

- Fixes build with Bevy 0.16.0-rc5
Micro PR, just adapts to bevyengine/bevy#18813, ~and removes a couple of unused imports~.

Updated to Bevy 0.16.0-rc.5

---

src/collision/collider/collider_hierarchy/plugin.rs

Fixes #713
`ColliderOf` is sometimes not inserted correctly for rigid body descendants if the `Collider` is added after the initial spawn, which is often the case for e.g. `ColliderConstructorHierarchy`.
Change the observer to traverse ancestors when `ColliderMarker` is added, to determine whether `ColliderOf` should be inserted.

Fix `ColliderOf` not being inserted when `Collider` is added to child

---

src/position.rs

- Add Ease implementation on Position/Rotation so that they work well with bevy easing functions.

Add Ease implementations on Position/Rotation

---

README.md
crates/avian2d/Cargo.toml
crates/avian2d/examples/debugdump_2d.rs
crates/avian3d/Cargo.toml
crates/avian3d/examples/debugdump_3d.rs
src/collision/narrow_phase/mod.rs
src/dynamics/rigid_body/mass_properties/components/collider.rs
src/dynamics/rigid_body/mass_properties/components/mod.rs
src/lib.rs
src/spatial_query/ray_caster.rs
src/spatial_query/shape_caster.rs

Update version numbers and dependencies, and do final release prep.

Release v0.3.0

---

src/interpolation.rs

I want to place something in AfterFixedMainLoop and order it relative to the interpolation
Export the relevant system set

Export TransformEasingSet

---

.github/workflows/ci.yml
Cargo.lock

Also, whoops, the initial `Cargo.lock` I committed was outdated. Ironic :D

Improve CI caching

---

crates/avian3d/examples/custom_constraint.rs
src/dynamics/solver/joints/distance.rs
src/dynamics/solver/joints/point_constraint.rs
src/dynamics/solver/joints/prismatic.rs
src/dynamics/solver/joints/spherical.rs

Solution to a bug me and @Jondolf hunted

Account for COM in constrants center difference

---

src/dynamics/rigid_body/forces/mod.rs
src/dynamics/rigid_body/forces/tests.rs

#770 added a `Forces` helper. We should have tests to verify that it actually produces the correct results!
Add some unit tests for `Forces`.

Add tests for `Forces`

---

src/collision/collider/collider_hierarchy/mod.rs

Add read-only access to the entities inside `RigidBodyColliders`.
Implement `Deref` and `IntoIterator` for `RigidBodyColliders`.

Implement `Deref` and `IntoIterator` for `RigidBodyColliders`

---

src/collision/broad_phase.rs

Fixes #786.
Disabling colliders is currently bugged. After removing `Disabled`/`ColliderDisabled`, they do not work again. This is because the queries in the observers responsible for re-enabling are incorrectly filtering out disabled entities.
Fix the observers. There's some nasty duplication since the queries have to be subtly different, but it can be cleaned up later.

Fix colliders not working after removing `Disabled`/`ColliderDisabled`

---

crates/avian2d/Cargo.toml
crates/avian2d/examples/tumbler.rs

Add the [tumbler](<https://github.com/erincatto/box2d/blob/fb8b81f03f126ff52db5ebd25c90928fb56528d5/shared/benchmarks.c#L494>) sample from Box2D.

Add `tumbler` example

---

Cargo.lock
benches/Cargo.toml
crates/avian2d/Cargo.toml
crates/avian3d/Cargo.toml
crates/examples_common_2d/Cargo.toml
crates/examples_common_3d/Cargo.toml

Update to the full Bevy 0.17 release from 0.17.0-rc.
Do that :)

Update to Bevy 0.17 from RC

---

src/dynamics/solver/plugin.rs

Fixes #841.
`JointDamping` currently requires both bodies to have a `SolverBody`, which is not the case for static bodies. It should use a dummy body for static bodies.
Use a dummy body for static bodies.

Fix damping for joints with a static body

---

src/dynamics/rigid_body/forces/query_data.rs

We have an `_at_point` version of applying forces and impulses, but not linear acceleration.
Add `apply_linear_acceleration_at_point`.

Add `apply_linear_acceleration_at_point`
